# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/sebmar496/Desktop/leos/leos-S26-flight-computer/external/leos_cyphal_types/leos/efm/1400.ADC.0.1.dsdl
#
# Generated at:  2026-04-03 14:48:40.943652 UTC
# Is deprecated: no
# Fixed port ID: 1400
# Full name:     leos.efm.ADC
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class ADC_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 location:           None | uavcan.primitive.String_1_0 = None,
                 valid:              None | bool = None,
                 adc1_ch1_diff:      None | int | float | _np_.float32 = None,
                 adc1_ch2_sensing:   None | int | float | _np_.float32 = None,
                 adc1_ch3_reference: None | int | float | _np_.float32 = None,
                 adc1_ch4_breakbeam: None | int | float | _np_.float32 = None,
                 adc2_ch1_diff:      None | int | float | _np_.float32 = None,
                 adc2_ch2_sensing:   None | int | float | _np_.float32 = None,
                 adc2_ch3_reference: None | int | float | _np_.float32 = None,
                 adc2_ch4_breakbeam: None | int | float | _np_.float32 = None) -> None:
        """
        leos.efm.ADC.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param location:           uavcan.primitive.String.1.0 location
        :param valid:              bool valid
        :param adc1_ch1_diff:      saturated float32 adc1_ch1_diff
        :param adc1_ch2_sensing:   saturated float32 adc1_ch2_sensing
        :param adc1_ch3_reference: saturated float32 adc1_ch3_reference
        :param adc1_ch4_breakbeam: saturated float32 adc1_ch4_breakbeam
        :param adc2_ch1_diff:      saturated float32 adc2_ch1_diff
        :param adc2_ch2_sensing:   saturated float32 adc2_ch2_sensing
        :param adc2_ch3_reference: saturated float32 adc2_ch3_reference
        :param adc2_ch4_breakbeam: saturated float32 adc2_ch4_breakbeam
        """
        self._location:           uavcan.primitive.String_1_0
        self._valid:              bool
        self._adc1_ch1_diff:      float
        self._adc1_ch2_sensing:   float
        self._adc1_ch3_reference: float
        self._adc1_ch4_breakbeam: float
        self._adc2_ch1_diff:      float
        self._adc2_ch2_sensing:   float
        self._adc2_ch3_reference: float
        self._adc2_ch4_breakbeam: float

        if location is None:
            self.location = uavcan.primitive.String_1_0()
        elif isinstance(location, uavcan.primitive.String_1_0):
            self.location = location
        else:
            raise ValueError(f'location: expected uavcan.primitive.String_1_0 '
                             f'got {type(location).__name__}')

        self.valid = valid if valid is not None else False

        self.adc1_ch1_diff = adc1_ch1_diff if adc1_ch1_diff is not None else 0.0  # type: ignore

        self.adc1_ch2_sensing = adc1_ch2_sensing if adc1_ch2_sensing is not None else 0.0  # type: ignore

        self.adc1_ch3_reference = adc1_ch3_reference if adc1_ch3_reference is not None else 0.0  # type: ignore

        self.adc1_ch4_breakbeam = adc1_ch4_breakbeam if adc1_ch4_breakbeam is not None else 0.0  # type: ignore

        self.adc2_ch1_diff = adc2_ch1_diff if adc2_ch1_diff is not None else 0.0  # type: ignore

        self.adc2_ch2_sensing = adc2_ch2_sensing if adc2_ch2_sensing is not None else 0.0  # type: ignore

        self.adc2_ch3_reference = adc2_ch3_reference if adc2_ch3_reference is not None else 0.0  # type: ignore

        self.adc2_ch4_breakbeam = adc2_ch4_breakbeam if adc2_ch4_breakbeam is not None else 0.0  # type: ignore

    @property
    def location(self) -> uavcan.primitive.String_1_0:
        """
        uavcan.primitive.String.1.0 location
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._location

    @location.setter
    def location(self, x: uavcan.primitive.String_1_0) -> None:
        if isinstance(x, uavcan.primitive.String_1_0):
            self._location = x
        else:
            raise ValueError(f'location: expected uavcan.primitive.String_1_0 got {type(x).__name__}')

    @property
    def valid(self) -> bool:
        """
        bool valid
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._valid

    @valid.setter
    def valid(self, x: bool) -> None:
        self._valid = bool(x)  # Cast to bool implements saturation

    @property
    def adc1_ch1_diff(self) -> float:
        """
        saturated float32 adc1_ch1_diff
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._adc1_ch1_diff

    @adc1_ch1_diff.setter
    def adc1_ch1_diff(self, x: int | float | _np_.float32) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._adc1_ch1_diff = x
        else:
            raise ValueError(f'adc1_ch1_diff: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    @property
    def adc1_ch2_sensing(self) -> float:
        """
        saturated float32 adc1_ch2_sensing
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._adc1_ch2_sensing

    @adc1_ch2_sensing.setter
    def adc1_ch2_sensing(self, x: int | float | _np_.float32) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._adc1_ch2_sensing = x
        else:
            raise ValueError(f'adc1_ch2_sensing: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    @property
    def adc1_ch3_reference(self) -> float:
        """
        saturated float32 adc1_ch3_reference
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._adc1_ch3_reference

    @adc1_ch3_reference.setter
    def adc1_ch3_reference(self, x: int | float | _np_.float32) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._adc1_ch3_reference = x
        else:
            raise ValueError(f'adc1_ch3_reference: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    @property
    def adc1_ch4_breakbeam(self) -> float:
        """
        saturated float32 adc1_ch4_breakbeam
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._adc1_ch4_breakbeam

    @adc1_ch4_breakbeam.setter
    def adc1_ch4_breakbeam(self, x: int | float | _np_.float32) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._adc1_ch4_breakbeam = x
        else:
            raise ValueError(f'adc1_ch4_breakbeam: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    @property
    def adc2_ch1_diff(self) -> float:
        """
        saturated float32 adc2_ch1_diff
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._adc2_ch1_diff

    @adc2_ch1_diff.setter
    def adc2_ch1_diff(self, x: int | float | _np_.float32) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._adc2_ch1_diff = x
        else:
            raise ValueError(f'adc2_ch1_diff: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    @property
    def adc2_ch2_sensing(self) -> float:
        """
        saturated float32 adc2_ch2_sensing
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._adc2_ch2_sensing

    @adc2_ch2_sensing.setter
    def adc2_ch2_sensing(self, x: int | float | _np_.float32) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._adc2_ch2_sensing = x
        else:
            raise ValueError(f'adc2_ch2_sensing: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    @property
    def adc2_ch3_reference(self) -> float:
        """
        saturated float32 adc2_ch3_reference
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._adc2_ch3_reference

    @adc2_ch3_reference.setter
    def adc2_ch3_reference(self, x: int | float | _np_.float32) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._adc2_ch3_reference = x
        else:
            raise ValueError(f'adc2_ch3_reference: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    @property
    def adc2_ch4_breakbeam(self) -> float:
        """
        saturated float32 adc2_ch4_breakbeam
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._adc2_ch4_breakbeam

    @adc2_ch4_breakbeam.setter
    def adc2_ch4_breakbeam(self, x: int | float | _np_.float32) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._adc2_ch4_breakbeam = x
        else:
            raise ValueError(f'adc2_ch4_breakbeam: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.location._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.add_unaligned_bit(self.valid)
        if _np_.isfinite(self.adc1_ch1_diff):
            if self.adc1_ch1_diff > 340282346638528859811704183484516925440.0:
                _ser_.add_unaligned_f32(340282346638528859811704183484516925440.0)
            elif self.adc1_ch1_diff < -340282346638528859811704183484516925440.0:
                _ser_.add_unaligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_unaligned_f32(self.adc1_ch1_diff)
        else:
            _ser_.add_unaligned_f32(self.adc1_ch1_diff)
        if _np_.isfinite(self.adc1_ch2_sensing):
            if self.adc1_ch2_sensing > 340282346638528859811704183484516925440.0:
                _ser_.add_unaligned_f32(340282346638528859811704183484516925440.0)
            elif self.adc1_ch2_sensing < -340282346638528859811704183484516925440.0:
                _ser_.add_unaligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_unaligned_f32(self.adc1_ch2_sensing)
        else:
            _ser_.add_unaligned_f32(self.adc1_ch2_sensing)
        if _np_.isfinite(self.adc1_ch3_reference):
            if self.adc1_ch3_reference > 340282346638528859811704183484516925440.0:
                _ser_.add_unaligned_f32(340282346638528859811704183484516925440.0)
            elif self.adc1_ch3_reference < -340282346638528859811704183484516925440.0:
                _ser_.add_unaligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_unaligned_f32(self.adc1_ch3_reference)
        else:
            _ser_.add_unaligned_f32(self.adc1_ch3_reference)
        if _np_.isfinite(self.adc1_ch4_breakbeam):
            if self.adc1_ch4_breakbeam > 340282346638528859811704183484516925440.0:
                _ser_.add_unaligned_f32(340282346638528859811704183484516925440.0)
            elif self.adc1_ch4_breakbeam < -340282346638528859811704183484516925440.0:
                _ser_.add_unaligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_unaligned_f32(self.adc1_ch4_breakbeam)
        else:
            _ser_.add_unaligned_f32(self.adc1_ch4_breakbeam)
        if _np_.isfinite(self.adc2_ch1_diff):
            if self.adc2_ch1_diff > 340282346638528859811704183484516925440.0:
                _ser_.add_unaligned_f32(340282346638528859811704183484516925440.0)
            elif self.adc2_ch1_diff < -340282346638528859811704183484516925440.0:
                _ser_.add_unaligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_unaligned_f32(self.adc2_ch1_diff)
        else:
            _ser_.add_unaligned_f32(self.adc2_ch1_diff)
        if _np_.isfinite(self.adc2_ch2_sensing):
            if self.adc2_ch2_sensing > 340282346638528859811704183484516925440.0:
                _ser_.add_unaligned_f32(340282346638528859811704183484516925440.0)
            elif self.adc2_ch2_sensing < -340282346638528859811704183484516925440.0:
                _ser_.add_unaligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_unaligned_f32(self.adc2_ch2_sensing)
        else:
            _ser_.add_unaligned_f32(self.adc2_ch2_sensing)
        if _np_.isfinite(self.adc2_ch3_reference):
            if self.adc2_ch3_reference > 340282346638528859811704183484516925440.0:
                _ser_.add_unaligned_f32(340282346638528859811704183484516925440.0)
            elif self.adc2_ch3_reference < -340282346638528859811704183484516925440.0:
                _ser_.add_unaligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_unaligned_f32(self.adc2_ch3_reference)
        else:
            _ser_.add_unaligned_f32(self.adc2_ch3_reference)
        if _np_.isfinite(self.adc2_ch4_breakbeam):
            if self.adc2_ch4_breakbeam > 340282346638528859811704183484516925440.0:
                _ser_.add_unaligned_f32(340282346638528859811704183484516925440.0)
            elif self.adc2_ch4_breakbeam < -340282346638528859811704183484516925440.0:
                _ser_.add_unaligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_unaligned_f32(self.adc2_ch4_breakbeam)
        else:
            _ser_.add_unaligned_f32(self.adc2_ch4_breakbeam)
        _ser_.pad_to_alignment(8)
        assert 280 <= (_ser_.current_bit_length - _base_offset_) <= 2328, \
            'Bad serialization of leos.efm.ADC.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> ADC_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "location"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.primitive.String_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "valid"
        _f1_ = _des_.fetch_unaligned_bit()
        # Temporary _f2_ holds the value of "adc1_ch1_diff"
        _f2_ = _des_.fetch_unaligned_f32()
        # Temporary _f3_ holds the value of "adc1_ch2_sensing"
        _f3_ = _des_.fetch_unaligned_f32()
        # Temporary _f4_ holds the value of "adc1_ch3_reference"
        _f4_ = _des_.fetch_unaligned_f32()
        # Temporary _f5_ holds the value of "adc1_ch4_breakbeam"
        _f5_ = _des_.fetch_unaligned_f32()
        # Temporary _f6_ holds the value of "adc2_ch1_diff"
        _f6_ = _des_.fetch_unaligned_f32()
        # Temporary _f7_ holds the value of "adc2_ch2_sensing"
        _f7_ = _des_.fetch_unaligned_f32()
        # Temporary _f8_ holds the value of "adc2_ch3_reference"
        _f8_ = _des_.fetch_unaligned_f32()
        # Temporary _f9_ holds the value of "adc2_ch4_breakbeam"
        _f9_ = _des_.fetch_unaligned_f32()
        self = ADC_0_1(
            location=_f0_,
            valid=_f1_,
            adc1_ch1_diff=_f2_,
            adc1_ch2_sensing=_f3_,
            adc1_ch3_reference=_f4_,
            adc1_ch4_breakbeam=_f5_,
            adc2_ch1_diff=_f6_,
            adc2_ch2_sensing=_f7_,
            adc2_ch3_reference=_f8_,
            adc2_ch4_breakbeam=_f9_)
        _des_.pad_to_alignment(8)
        assert 280 <= (_des_.consumed_bit_length - _base_offset_) <= 2328, \
            'Bad deserialization of leos.efm.ADC.0.1'
        assert isinstance(self, ADC_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'location=%s' % self.location,
            'valid=%s' % self.valid,
            'adc1_ch1_diff=%s' % self.adc1_ch1_diff,
            'adc1_ch2_sensing=%s' % self.adc1_ch2_sensing,
            'adc1_ch3_reference=%s' % self.adc1_ch3_reference,
            'adc1_ch4_breakbeam=%s' % self.adc1_ch4_breakbeam,
            'adc2_ch1_diff=%s' % self.adc2_ch1_diff,
            'adc2_ch2_sensing=%s' % self.adc2_ch2_sensing,
            'adc2_ch3_reference=%s' % self.adc2_ch3_reference,
            'adc2_ch4_breakbeam=%s' % self.adc2_ch4_breakbeam,
        ])
        return f'leos.efm.ADC.0.1({_o_0_})'

    _FIXED_PORT_ID_ = 1400
    _EXTENT_BYTES_ = 300

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
        'ABzY8NYl@00{`t=O;8(G64v|+@Q<)#n<RETNt{@YjS$3faDFx<P8@bSoe(=taoFrIk_O&jX{2aIF4)>sk;87`)Ku-HGF!!wBS&)M'
        '$dMztapbVsWp}H#$kra%leeEF1QL?tAFy{5I6Td~?*6)8zvj(+QcuZ$I+=`=|NPU1$&8!HCJfgq+Gf`Nt(nSN2_v1)74oj_S)qUM'
        'T`Ozn=rZ%kWWfr*3D12Qei6of)vz7MDuyiLAH41rOKGoEwCYt9!!dINaUg5u-GnuoOT7K=mC%nGx2&RT=N)dVeOkT#CWHtGe+a(}'
        '{SL$QyrP{dd6pY~MnEm1tZ9Y5a@Dr7nJw4tM#l6^!{hNVtuo2l{SzhgR@!tDg(6>)ealKv=(aN!vIFc82oT}^S?6aVJ65&n@}F+u'
        'yjV0RL;u95Ce6~!2bMGDvA6kbeHIQHR@TZ{j#r7M)naNPh5peSj%$xOR_2$EXN_6Kdb|!JWqU@p>@I{TEj4Yro{`IEXsKuY<3pQ3'
        '+$?d0WXMH4zrPQ!h5i$U>zPi*EM~R?O_x%B8zB|UwCzoX7!mv<Rhco$b6d^jxoTc6K#X;>9uPPt>*MCKk;=NE|KjHQw$N#*UgJHL'
        '#XGiF$=Y?gt*+0PjC>*V^;RJ6WG<D@+G)xXTDd%B&!g)3s9+UMFJIhVo@r)NMX&+?*p<AKHa*K}s>)Z*HH((RYmM{|e^|<9&En(^'
        'P1U$%W=mH1$1o1Dz)i7ts>yhdtWI1roiXd0Rj@p}RY*6DoH@aBOBPt3WkVb+N?_##=4^+yiC>iUqQ1uWwUjkE00>++5`b9!l**q}'
        'wqgKsbxx_xfdp~@YUN(!*IJzn6i@?*R_)q$$UvjGpuJ{KGj!k4R1eyqJ%9rhS(N)a*isKV;6MO}>Tqe6<__Q01`fiZ0Af`i0d)ST'
        'HXNpHf+IUTk%Z=t-jh9a!jS-;sOZWhKfrB|-Lowmg(m_y-ZTc1lI+BNVZkvt9zfS-rYV*u@7o?uKvw`ywTy{0NdEK#;lh*fQ~)RI'
        '@<md@JN3YL@HCtZ;F-I|OIoCJ`k{QlDR?FTy_Q=Z^|KF+2&X|0;JFHpez*9!_vd%TA3O`s1#o85=eB*|S$bjDe8BT?CV&@zbZ5vy'
        'CvDO_yQ{w81$Z%l_~tsRdv<QueZX0W2k_E8uahiD|NNfB0q5YQ04{9p?HR(1Z{OeUJ@X6a;X(k3`^p1ZkxkE@#suAv2q3vt2k}ZJ'
        '^zOM==z(MaefOOavLw5gA4z=B3w;4x+*vX75=YW%)x7e^Vu6?8VgQ#OC}(6%wy!?YSm7186hMD{btQRyU4G<oz^l+7z-tejJ3=7)'
        '*B?vVa2Z|;;EmRGc#(Yc^IClKvBd|k!y5to;-T_OD1`CWV_gHh3BL$nU`Nf;?w5!%S`!7+Df8~K21Z1T$QV(Hb3hcMB1UE0P%x@O'
        '3}Yh3WQ?iMg<T?c$=Idhh6Xz7BI+{gD#S4^VqC_!3Q0_gn3OT8LO=G4*e_$h3IjMG;(&|;Dh%SFh=Vc?sxX8@A`Zzoq{1)`i#ROf'
        'unHqMBI1aQBPuXtA~G473I!~PSdg)x!URr;I3eSN3R5^G;*^Y2Doo?Fh|@Aos}NuyVjyFn!VJ!cI3weX3bQyX;;f9bD$L=Wh;uT|'
        'sW6Z8BF@V=ufhT@h`1o*f(nbcDB_}wiz+PPl88$(E~&7L%OWnzxU9kou86oI<BAHaxGLhRjH@cF;hKnRGOnqxj_V?>%ebz>25yMB'
        'LHVTY3K)?vqF_YBsDM!kqm*O~V*<t`j42q?uuH%$3A+^R(oh#rmrz$w*Dx+%T*A15aSf9KCM8TNnAEUez<vq)73|k=K)?YB2NWF8'
        'a8STO2?rG%)Nn|^Aqj^R9MW)Dz+nl86&%)ZM8FXVM-&{<kO{~nWC}733j!7-EGSsea6-Td2`3bs&~Qq?DG8?(oYHVwz-bAm6`a;E'
        '5HOH1P%zMNM!*>fXB3>#a8|%s31=0Y)o@P0ISJ<!oYQb#z<CMh6`a>_LBItG7ZhC3a8bZT2^SSy)No0_B?*@lT+(n^z-0-S6<pSE'
        'MZgsaHzZt9a7Dva0aqnlRd7|qH38QoTvKpO!*v1IC0ti<UBe9_D5WeS?7xN>`wU}I_M873J{{#eYM)O(0zMt9<YAvr?*X5txA97L'
        'ca=};KlY5?13s<S@54`)PwQLXf&6UvG+*->LXOw(@6Vb~^PI#tD`B5cH}L8DirMGW_sgd%r%aq=v3)-M5PZ7wRNCj$kAhEcorqOF'
        '&1PwOJB23RjM3;OhZd_GS|#GanKUQSWil;4P8v=0nRqlO({ghf&FOQMN$=C>pDK;6aA+da_e`VtFV(EwS1Lb+`?8VAr$avymQtpF'
        'bX((wk(#Wue|!<LKeN-W-(h5|Leb*C#Am|W{vl)3p0F}TAz$<iI}?8BcN%WKR7_hW$XZ6h^jPR0;vZQ%l`yjTw3!Y4wxPUhPYiM4'
        'H=+N#o*S-JbbDMYl{1SMFJJ0;*K%)q`9cqGIVlg_*ZVGYk7n&L=5_P77K*LdV@=TLnAx5}DV4R;M$sB8WqDv*Z6j_^rB|e<)|k;#'
        '=@m)zCXxx>oDi1VDUKS<bSc^*@9>~tZrN!oyv@G%zj|B0@yXTxZp%sMGgd}-%hq~+RQJezqW!w<q%GZJ)~3XE^&-!ZOGu<|y1J=n'
        'CMkz@S}%8-aNE=*<@SPZdtBYgd%9D~X1i%MIosh2Na!EfH!Xe0bSYg`<V5Jl%6n1i>v0Ib(pRHamPlFM)_tN@TVgE#M0pboFK-m{'
        'd9RG%7ED?m`=_7U`^=Z~%PzAwDxDH<)wNq39x^i-3Uf!B1xc^?QHs1Q4k22q|JrBs8yc6*epsvKD6cNB+>-P?`wLCg+JD$tzvG>J'
        'K5LmyT^kO&00Qe~y{zwc?f-$QxQTh&)okAM8jbae@wDG=<jgV0_DUJbecNc!O!GM0(2riNUX$5ZossQ-ckbLN_exz0%f1hqnRKs_'
        'X1zwn9v$5g!}w7l64~K+{5Z{yKS{&g!DChMJ}Pd<E%!?8D*llw{>xMfqZa)a@%q{m4;PJ8(K2tQEHk&u9{2|I?d1ma?ePZm?fC}u'
        'HQfM<{goicqXfZ@k00i6ZG1S%hZrB8=ff#Jyu^nyeCXxFc|P>>p^p!5@!>KbuJU1k56Fl2X(+M3-DZEMhcEjF9bMUnJ-WDtk)A9t'
        'Gh02d%7)fxuBZ26GReCf=@HSp^^joyy3N<i{>=|vnJb6BMCvs1j!29Bhr;@FZ^CMQijIq0oBH0i!}a}&=C61++`jT-RlYN>&@BiJ'
        '&#>~NtFD7k2;Axq9G#@qxuvxopg~jzpw|F;NvpRxK!d0Sz{jNZadUtMQ44_2N$d0G01cuR0AG{V*UbSML@fZmC9Q9p12l+Q0DMPU'
        '-!%tl5VZjKfwX>T4$vTK4uG8k-|e;rg!0=EaU+s-ZOJNcL9BxvU@_kP9H+y$t#$;TsvW%NYsc;7+9Au&*T->;kAFln{}YF+uNhp;'
        '@j@JF^N$nFsWi+N4Q81c`e^K&=FiXma?f=0x7+OpL*wRdQ@c^U8paFF8;Yq`BDB#XZ9Ct4D@CT0bgHfSTXEvQOJOIhColj2'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
