# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2026-03-13 02:09:03.049892 UTC
# Namespace:     leos.gps

from leos.gps.Fix_0_1 import Fix_0_1 as Fix_0_1

# Convenience aliases of the newest minor versions known at the time of code generation.
Fix_0 = Fix_0_1
