# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/vip/new_working/working/public_regulated_data_types/uavcan/metatransport/can/RTR.0.1.dsdl
#
# Generated at:  2025-11-15 03:18:06.697108 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.metatransport.can.RTR
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.metatransport.can

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class RTR_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 arbitration_id: None | uavcan.metatransport.can.ArbitrationID_0_1 = None) -> None:
        """
        uavcan.metatransport.can.RTR.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param arbitration_id: uavcan.metatransport.can.ArbitrationID.0.1 arbitration_id
        """
        self._arbitration_id: uavcan.metatransport.can.ArbitrationID_0_1

        if arbitration_id is None:
            self.arbitration_id = uavcan.metatransport.can.ArbitrationID_0_1()
        elif isinstance(arbitration_id, uavcan.metatransport.can.ArbitrationID_0_1):
            self.arbitration_id = arbitration_id
        else:
            raise ValueError(f'arbitration_id: expected uavcan.metatransport.can.ArbitrationID_0_1 '
                             f'got {type(arbitration_id).__name__}')

    @property
    def arbitration_id(self) -> uavcan.metatransport.can.ArbitrationID_0_1:
        """
        uavcan.metatransport.can.ArbitrationID.0.1 arbitration_id
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._arbitration_id

    @arbitration_id.setter
    def arbitration_id(self, x: uavcan.metatransport.can.ArbitrationID_0_1) -> None:
        if isinstance(x, uavcan.metatransport.can.ArbitrationID_0_1):
            self._arbitration_id = x
        else:
            raise ValueError(f'arbitration_id: expected uavcan.metatransport.can.ArbitrationID_0_1 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.arbitration_id._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 40 <= (_ser_.current_bit_length - _base_offset_) <= 40, \
            'Bad serialization of uavcan.metatransport.can.RTR.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> RTR_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "arbitration_id"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.metatransport.can.ArbitrationID_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = RTR_0_1(
            arbitration_id=_f0_)
        _des_.pad_to_alignment(8)
        assert 40 <= (_des_.consumed_bit_length - _base_offset_) <= 40, \
            'Bad deserialization of uavcan.metatransport.can.RTR.0.1'
        assert isinstance(self, RTR_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'arbitration_id=%s' % self.arbitration_id,
        ])
        return f'uavcan.metatransport.can.RTR.0.1({_o_0_})'

    _EXTENT_BYTES_ = 5

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8?(i3B0{`urU2h!K8OLW|z3bOF#y}ybJf$=}A+U~<l$TN<FMx=)Nz;&^NQI7OcaD9=-JMxxW{pjS1Q%3^G*T^PkPyA>MfnIw'
        '{Q`Uh`VDf$HBxVSX6OIJ>$TllZPS}hB<FuTJ9FmDnfd+pIlKO(`uTUKtkJ*Zslm1zxxJPhsnBzJ-bYTSr&@M5=nsO(i&dJ;y%UGS'
        'ZafUt&Fz6o@1>_cO+QX$QnP)hZ(ct!bT+$=-|DN_i9^Sa20<9NvMo1m-bj;%y{W>;3;a}D$<(`O-%Hz8yYz?j(=?f}oj4A?&M;O{'
        '`hI%Yh#u^eCbhRb)pK`8GHts~?AUQOJadxfE#I7C&tP>eIeF+XFNPh@Y>CZ5SKdhVly36a^z8fQ*kkBpNtYk=_Uxg(U2-CI<Q@;Z'
        '*g@#^z1Z6{7rS)JkGyqXxmWyHt*dbFO_;IGne3kO*JGWwXUtS|ohY{ZforDXWb){B?kGE~b=kajHG9cSf9bQ-+?_}4D0Y0;3ElCI'
        '?hZTV8f%+QZ)iqPwcVhbCRS>;&L^|i9oO~z^}YANT*?y%U&?0Sx#lT&*TneH_38F<WX__`>vQ`2u%nWtvFE_<Z0Apx+3~D?CNkIQ'
        'szIo_PORMYZZdDLd0Wc0vst%I|JRa5I|_zjSD6=j${sl8Dw6pudS0hx_kym|OOxhx^Gt7D&tANjCjAv1^wr9yH(2r2hxUg-_&al5'
        'E1ZL2r{{I;P^}Mp*=ctlvS=m0`zw3y{z|rG-`#JWX|1-hc}Yj}y<}@AGQ$g%A7>M_>2+0lSD#CcudY6C4kOPsuXt;o3R`J%Y%~cu'
        'jK0~P@gb9Xes)9Vp7W<kWwdp1{}ZT^$3|0P$AKLNK|Ja<8aU?M`px9Re>xBOrB&@tFG`b>{21&$Pv%17$=}mt_L3L>a`gK<=2tux'
        'NyQEZX+no}5^eW8ff<gO$*Za#n1?L8#9s}Rxz-@u<)UtPwP&7B{a&(w2X^01+R?v#(0VUfz8v`3^W`7dWzx)hG&e5031dfg$NE^f'
        'HthABaC_g;bvuXYkEv|W>_i=-#X&wSL*lSwCa>@L8NjCDY-Nq93}Q3mS>NqacAT}-E@xTVX;-o=@3gB~R(9GoY_Dfo+i6c_S>0(j'
        '@Ol&bPh-Cs^f#N2r#*+9M=l_bAs3OykxR%&kjuzNk&huCNB#i$1oBDb38X;&5cw36kUv5`jr=k48RSopCy_rzO5`czv&hrP=aA1M'
        'TgVmU8RRPREb<)kJo0DA7mzO^UqZf&{5kR!<S&q~B40zkj=X?;8+jY4kz2?+$S;szA-_g`gZvhGANhTrR~scX9_NPS#!K9In;W;e'
        'p}DcejXT`<f*W6P<7;kw!;Npbai1ICqcJq^V`^()#Fo_x*w)ce{?4(PZCExCDf0%h-6s8!`T6}mOsok^EMQUwCgllCEMQUtCS_nU'
        '4NMxqqz+7~z@!XJEMT$#Oy+^f959)kz+@VjG=WJ2m`nkaIxwjLlPWN&0FyE>DFG7;m=G`_U_!uzfC&K;0wx4Z2$&EsAz(tlgn$VF'
        '69Og#ObD0|Fd<+<z=VJa0TTiy1WX8+5HKNNLcoN82>}xVCIn0fm=G`_U_!uzfC&K;0wx4Z2$&EsAz(tlgcuWIOo%Zd#)KFXVoZoJ'
        'A;yFl6Jkt=F(Jl;7!zVlh%q6?gm#AdZ)kM%R=Y7QXeekXXfQNHozViO+A)=Iny)VoT*b8xUB$h*WeP!8xkq0cO0-V5g?>(-(W`qF'
        'Q5eJv4|acrS3#9Mt04W_$LYpjN|v?pXY*gAFWl7^ujxysO8?*?tX2-Z%DpQVePy&dIs5Xy)roE&VKK6N@I)&8>;KxqL*LT3^U3_p'
        'fmQkLHZR|;cUb*CUS9}PUl^&DMp6|<s^S2tPFCV2NVPgqiI*VN+C(MZgjA;>)f%K)fmBP7>O7=62dU0ZRN~W+Y7<gzK&n%aY8_Io'
        'L8?_qwF0S@A=MJ3YC)<3QWcP@fK&yfDj-z>sR~F{K&k>#6_BccR0X6eAXNdW3P@Ezssd6Kkg9-G1*9q<RRO6ANL4_p0#X%_s(@4l'
        'q$(g)0jUZ|RY0l&QWcP@fK&yfDj-z>sR~F{K&k>#6_BccR0X6eAXNdW3YMy1sS1{=V5th0s$i)Kma1T>3YMy1sS1{=V5th0s$i)K'
        'ma1T>3YMyvEWay7`CSwoMZr;&-vtc?4TqH94Tah-9V>3-#+RnB)h9OYmrarTC(|B|6}jF+D02U0aeLzO#cQ+{I(<dX?!L5^eZg_W'
        'GI#FbmAA=)9XspxXf*hWYj>&9$d?*-%zXb_Rq*&*dLyfN$3GCC8-0&9`B8R$puO=|bL)x<pm1K{ypi*A6r@2x{u2~R6DU|fp$Zgg'
        '6DU-Hf;F*FtOA7+P?!Y@(?FpC6zV{s3KYsf!2$|PK;bx0SOf~kfWiV$m<I}TKw);`E1PMc&;$w%pfCj#>Oi3e6ska>0u;(Xp#&5x'
        'pdf*Q1PT%;NT48rf&>Z@C`h0nfr11I5-3QZAc2Ae3KA$tpdf*Q1PT%;NT48rf&>Z@C`h0nfr11I5-3QZAc2Ae3KA$tpdf*Q1PT%;'
        'NJc?23X)NfjDlnoB%>f11<5E#MnN(Pl2MS1f@BmVqaYat$tXxhL5>&01q}ra|MxVY7@i+1EwjH^$xC8q^m(tWnu>UF{KH=RA=JS)'
        'Zr(Vk`hE3s&xs<hOQGrqv7*sIeJ{$sdNtcV7^)~H=?5{nYR&VNOKU+$S;_p?8>fy~9#^uz1p6O;=DYECv$!ZURA{Ks(71+L{{W^>'
        '1i<+z000'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
