# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2026-03-13 02:09:03.052301 UTC
# Namespace:     leos.service

from leos.service.Cutdown_0_1 import Cutdown_0_1 as Cutdown_0_1

# Convenience aliases of the newest minor versions known at the time of code generation.
Cutdown_0 = Cutdown_0_1
