# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/sebmar496/Desktop/leos-S26-flight-computer/external/leos_cyphal_types/leos/sensors/1208.BME688.0.1.dsdl
#
# Generated at:  2026-03-13 02:09:03.059321 UTC
# Is deprecated: no
# Fixed port ID: 1208
# Full name:     leos.sensors.BME688
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive
import uavcan.si.unit.length
import uavcan.si.unit.pressure
import uavcan.si.unit.temperature

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class BME688_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 board_ms:       None | int | _np_.uint32 = None,
                 location:       None | uavcan.primitive.String_1_0 = None,
                 humidity:       None | int | float | _np_.float32 = None,
                 pressure:       None | uavcan.si.unit.pressure.Scalar_1_0 = None,
                 temperature:    None | uavcan.si.unit.temperature.Scalar_1_0 = None,
                 altitude:       None | uavcan.si.unit.length.Scalar_1_0 = None,
                 gas_resistance: None | int | float | _np_.float32 = None) -> None:
        """
        leos.sensors.BME688.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param board_ms:       saturated uint32 board_ms
        :param location:       uavcan.primitive.String.1.0 location
        :param humidity:       saturated float32 humidity
        :param pressure:       uavcan.si.unit.pressure.Scalar.1.0 pressure
        :param temperature:    uavcan.si.unit.temperature.Scalar.1.0 temperature
        :param altitude:       uavcan.si.unit.length.Scalar.1.0 altitude
        :param gas_resistance: saturated float32 gas_resistance
        """
        self._board_ms:       int
        self._location:       uavcan.primitive.String_1_0
        self._humidity:       float
        self._pressure:       uavcan.si.unit.pressure.Scalar_1_0
        self._temperature:    uavcan.si.unit.temperature.Scalar_1_0
        self._altitude:       uavcan.si.unit.length.Scalar_1_0
        self._gas_resistance: float

        self.board_ms = board_ms if board_ms is not None else 0  # type: ignore

        if location is None:
            self.location = uavcan.primitive.String_1_0()
        elif isinstance(location, uavcan.primitive.String_1_0):
            self.location = location
        else:
            raise ValueError(f'location: expected uavcan.primitive.String_1_0 '
                             f'got {type(location).__name__}')

        self.humidity = humidity if humidity is not None else 0.0  # type: ignore

        if pressure is None:
            self.pressure = uavcan.si.unit.pressure.Scalar_1_0()
        elif isinstance(pressure, uavcan.si.unit.pressure.Scalar_1_0):
            self.pressure = pressure
        else:
            raise ValueError(f'pressure: expected uavcan.si.unit.pressure.Scalar_1_0 '
                             f'got {type(pressure).__name__}')

        if temperature is None:
            self.temperature = uavcan.si.unit.temperature.Scalar_1_0()
        elif isinstance(temperature, uavcan.si.unit.temperature.Scalar_1_0):
            self.temperature = temperature
        else:
            raise ValueError(f'temperature: expected uavcan.si.unit.temperature.Scalar_1_0 '
                             f'got {type(temperature).__name__}')

        if altitude is None:
            self.altitude = uavcan.si.unit.length.Scalar_1_0()
        elif isinstance(altitude, uavcan.si.unit.length.Scalar_1_0):
            self.altitude = altitude
        else:
            raise ValueError(f'altitude: expected uavcan.si.unit.length.Scalar_1_0 '
                             f'got {type(altitude).__name__}')

        self.gas_resistance = gas_resistance if gas_resistance is not None else 0.0  # type: ignore

    @property
    def board_ms(self) -> int:
        """
        saturated uint32 board_ms
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._board_ms

    @board_ms.setter
    def board_ms(self, x: int | _np_.uint32) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 4294967295:
            self._board_ms = x
        else:
            raise ValueError(f'board_ms: value {x} is not in [0, 4294967295]')

    @property
    def location(self) -> uavcan.primitive.String_1_0:
        """
        uavcan.primitive.String.1.0 location
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._location

    @location.setter
    def location(self, x: uavcan.primitive.String_1_0) -> None:
        if isinstance(x, uavcan.primitive.String_1_0):
            self._location = x
        else:
            raise ValueError(f'location: expected uavcan.primitive.String_1_0 got {type(x).__name__}')

    @property
    def humidity(self) -> float:
        """
        saturated float32 humidity
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._humidity

    @humidity.setter
    def humidity(self, x: int | float | _np_.float32) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._humidity = x
        else:
            raise ValueError(f'humidity: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    @property
    def pressure(self) -> uavcan.si.unit.pressure.Scalar_1_0:
        """
        uavcan.si.unit.pressure.Scalar.1.0 pressure
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._pressure

    @pressure.setter
    def pressure(self, x: uavcan.si.unit.pressure.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.pressure.Scalar_1_0):
            self._pressure = x
        else:
            raise ValueError(f'pressure: expected uavcan.si.unit.pressure.Scalar_1_0 got {type(x).__name__}')

    @property
    def temperature(self) -> uavcan.si.unit.temperature.Scalar_1_0:
        """
        uavcan.si.unit.temperature.Scalar.1.0 temperature
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._temperature

    @temperature.setter
    def temperature(self, x: uavcan.si.unit.temperature.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.temperature.Scalar_1_0):
            self._temperature = x
        else:
            raise ValueError(f'temperature: expected uavcan.si.unit.temperature.Scalar_1_0 got {type(x).__name__}')

    @property
    def altitude(self) -> uavcan.si.unit.length.Scalar_1_0:
        """
        uavcan.si.unit.length.Scalar.1.0 altitude
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._altitude

    @altitude.setter
    def altitude(self, x: uavcan.si.unit.length.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.length.Scalar_1_0):
            self._altitude = x
        else:
            raise ValueError(f'altitude: expected uavcan.si.unit.length.Scalar_1_0 got {type(x).__name__}')

    @property
    def gas_resistance(self) -> float:
        """
        saturated float32 gas_resistance
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._gas_resistance

    @gas_resistance.setter
    def gas_resistance(self, x: int | float | _np_.float32) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._gas_resistance = x
        else:
            raise ValueError(f'gas_resistance: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.add_aligned_u32(max(min(self.board_ms, 4294967295), 0))
        _ser_.pad_to_alignment(8)
        self.location._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        if _np_.isfinite(self.humidity):
            if self.humidity > 340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(340282346638528859811704183484516925440.0)
            elif self.humidity < -340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_aligned_f32(self.humidity)
        else:
            _ser_.add_aligned_f32(self.humidity)
        _ser_.pad_to_alignment(8)
        self.pressure._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.temperature._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.altitude._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        if _np_.isfinite(self.gas_resistance):
            if self.gas_resistance > 340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(340282346638528859811704183484516925440.0)
            elif self.gas_resistance < -340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_aligned_f32(self.gas_resistance)
        else:
            _ser_.add_aligned_f32(self.gas_resistance)
        _ser_.pad_to_alignment(8)
        assert 208 <= (_ser_.current_bit_length - _base_offset_) <= 2256, \
            'Bad serialization of leos.sensors.BME688.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> BME688_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "board_ms"
        _f0_ = _des_.fetch_aligned_u32()
        # Temporary _f1_ holds the value of "location"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.primitive.String_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f2_ holds the value of "humidity"
        _f2_ = _des_.fetch_aligned_f32()
        # Temporary _f3_ holds the value of "pressure"
        _des_.pad_to_alignment(8)
        _f3_ = uavcan.si.unit.pressure.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f4_ holds the value of "temperature"
        _des_.pad_to_alignment(8)
        _f4_ = uavcan.si.unit.temperature.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f5_ holds the value of "altitude"
        _des_.pad_to_alignment(8)
        _f5_ = uavcan.si.unit.length.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f6_ holds the value of "gas_resistance"
        _f6_ = _des_.fetch_aligned_f32()
        self = BME688_0_1(
            board_ms=_f0_,
            location=_f1_,
            humidity=_f2_,
            pressure=_f3_,
            temperature=_f4_,
            altitude=_f5_,
            gas_resistance=_f6_)
        _des_.pad_to_alignment(8)
        assert 208 <= (_des_.consumed_bit_length - _base_offset_) <= 2256, \
            'Bad deserialization of leos.sensors.BME688.0.1'
        assert isinstance(self, BME688_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'board_ms=%s' % self.board_ms,
            'location=%s' % self.location,
            'humidity=%s' % self.humidity,
            'pressure=%s' % self.pressure,
            'temperature=%s' % self.temperature,
            'altitude=%s' % self.altitude,
            'gas_resistance=%s' % self.gas_resistance,
        ])
        return f'leos.sensors.BME688.0.1({_o_0_})'

    _FIXED_PORT_ID_ = 1208
    _EXTENT_BYTES_ = 400

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
        'ABzY8zj3o^0{`t>OKcn073KVCS(fSeC&x)Vjva?iY?5{yht8)_;?z}ob6v(xQY{*chU8dpWO7K%3|*;c3T4qk4hHC;o&qYm(JoqQ'
        'sil@$3SDWbrGOT#fG+B8n%>8uKBOeaKgq3Q0e&35`+4`?cis#Sc|9io@h|5S&A;GSeYEVAD;dMHT-&VJzcPyzD`S*u)q2gdeJcv~'
        'd}LMZDqWU88?9T>o#^z}(N|GAPz~F0EH`3_V9#~mZIt|mYqhH=hGSOA#r}#_^D>_0cs19{e2723n9oN+(zs>0o?Uae3+;>6^_>V3'
        'Ap9=+Itq3hrtiCUvEf@@^d<S*BG^@}C{V80R;9caL6=cBebexHSX-IbU7ntOiwF9-<Jm)wRsPuVts%>8PiMDLw0)yuIYT~+Kqu!V'
        ')ANmLt!zc?NN}jI;)t7NE|Uzoh-dWM=vovUFg)LM%BEXh?`XVHWL-hBSmX0mFA8L%Tq{LEA|k=Tcxl$lwANKuaJXUKDw$4ZHSP?R'
        '-*$!~*3EiAfCMid+xKO(W*r>eqH?Zljz+=ZFHD-HnNOM_eZXhiQ{Q7)6{~7Feq2g+wB`9FNU~$>1UpGt1iPpnb+csqqY);A;JH?Y'
        '#tptF8w^uqcpL;?nb=%5iWN%#)JmvpHKM5f&i7H!{h{s00bi%LtxyBWsMVuD-^z(MS}oQpHr01OTGbjA!Y9=ItZuocUvt-^yToil'
        '68lMT@N&&5nZD(0s>-wGny%$=jFSG|tBp#<bVoO6s>Us|(y*f6M`=ifUXgv=D#j;db@-a;3|ZH#y5-wjg>=)Xnj^fnWbs*Zmi?SN'
        'OOmr@0jst{VB;4}y=0(qbT%p`cK`y{O@tt}UZv(MAw~>AZp|sHb0C2nf*QXU`L)(20|nF&k}bPk8)TqST+p>@Pc!s>_ojNV3%Ww+'
        'j%7){)}Af(U^jG!(9`CZW@&EkJ#AnQ^n{RVtr5b$@70FAv`z5bhLuP{^ZW119`?a=AsmQxWs-Mu+k^LQ3;W?f2!}R}futlm{6N0o'
        'ARG#zccs!4%aI4Rhr`et!t-0kL>eSN`cQu12s|Ic3vKlxDfxTxq5Z*8cp-$B?inv>k<PJ4S_58$mqO52Ys;fP{>UET80aCq9Q)Dl'
        '6+d77#A8_xj>F3#oLpIR-9GRtz4F-BfD>>sgj3(UGi0HYHtD|lSl5PE;8Y0dl{{N}cKWfe0k1+jgxBsnPqHBW*S94OI1R6baAs|9'
        'Pm<5{`u#n-ZR^78a3+Mz1J!}7$R@k3F~M2LgpgaqK{`glxouw+vXBem`~z2nEXnST9f=Rl!TAs_Y(&f%@|{~j&6_(G3%mgrLb&))'
        'H6v@XeQQT!g*V}12>Et&<v6}B?RXsU7UV;C`=M(`9?1TkClWVYg119>cWWG8pf&Owi|;+L_~0FQH-sNOQhmt_`FQ_{<^b=(k3#6%'
        'fLYr81`%Itq;5J*zTVWpgop_l6Dn~INMcgNq>OhJOsbH=l!z%AQ!4aguZX=e_NsVS108h{bs2RP(wG)8En`}R9OgvK$(U0ik9iUE'
        'GUiq2!#)xFWb9L+ANxh@m$6@k0v1Fp$XHNe00%@Ika0kTK^zouP{u(O7%~x=j7)_()<vw#SXW^LM?@TvaYThN920R&#xWJfaa_c4'
        '8OK!!F%&VBF;rm!Cq$f(aYBVjoD^|V#z_^Xa7x4}8K+d3#%U3!Wt>)F24_T^k#R<aS)3JdR>oNs=5S8LIT`0vn8$e$=VhE%VF4FJ'
        'T##`=g+*KxaZ$!a6_#*G#3dP*R9MDk5tn6LR^cw*74a_Bld3CVLc)ZC2@R71CM8T#ku^*Sn36E1U`oSY0edCvRj^k>T|iwzT|r&L'
        'w18;|(+Z|F%n6v2FsEQn!@Pib3G)i(HS80xPr^P0`!wtquwTM{1^YED2w0G?pkP760Raaj98hpT!$AQDB^*?6P(vmllaMLMG^`6)'
        'm$0s2UBeLpM<g6ka74o~0mmd9Q*cbfaRJ9A99M8$!%)Cb!cf6b!wCT=B%DxiLc>V`CncOza8ko50jDIKQgBMcX#uAtoK|pJ!x;f*'
        'B%D!jM#EVFXC<6fa8|=P0p}!~Q*chhc>(7ooL6vO!vz5sB)lu(f`SVgE(*9P;i7_z8ZHUAB;k^ROByZ<xGdqag3B7-6~ac*BEnvR'
        '6f0vY$*lhyKAq$|>KUKj0Y06I>+p<EZv&sEPvdcQA1j~Mzwa5n4SZT}--oA`PwQ*nf&5_jG|%}Yc}}<Q?+=<!^O~erknoI8ckt<U'
        '#608E56Y+GyG)v7sb_rp5%_fcRC>mzcY;r^-4R=Snte;t>nSwxW=tkmIJDT}&?*rR&ZIesZjx#FNz!Pd&%~oSnU*)F(VRZFnDjFm'
        '{j}2Pm_rkpzHb`Mf2n3&ffD}|&Q7sc8$~nNzpmB8D2~Q`BVR@AuPo;UyN$9{cP;)Kd^x%u^cXkn5vy#}Yp!qD<>+d#&+uvuw`7r^'
        'Vi|SQXHn3@Un+JnV^nG-vl0cn3N_CjDRAMPDEMXebI)?UtY;OgrhDPi#q39xchj%cv%FX3?Dg{(&)%rmL(D(RTVW_HH*1a1=$Msk'
        'y-}>#CBwCb8WkSXT91jBje9e)tGyZ7xHltnE|bgfj)bV$39{c{rbmIgyrY8RxMi2D=r%hQeDi_+`Da)1XDz2xD_dpVYg+5I8@f-+'
        'XS%N2PRY`JX01qUPj`87Jn}^Prl*^Fd6dd$m-J?L2e&PbQd!UFw$Ig_ny)*JO64qNQ?(tQKt}(>zG>+N)1ykYJZGXH)!c@-7sw(1'
        'aTAUjr$_}|*EplLT2QRuaI^k~Uo+fV&2M_}>L#Vf{uz9^twnE^mi4jAac9Jpw)Tp>1+!eH2sgA<ko2cPl7eoEBS<#dzvfx_M#f{`'
        'UR_0Rl4Htmwk|aRysl5@NU-ZlrDpnV{WFZ7POUzfpv$P5Lyqk?%2c;qH(ayC9eGiZywbWRvv2k#*8hF?-FMBVsB2NYJZn_#GVin5'
        'u>4w^&`Yg0A<xb<Xt@jriPvzg%yrsi)4fNx(C|JXk=PLU@Bx|~K1{>CgH!8G7_A&__P4L1;nUpo1Pvbh`)&4*t8AIj@SE*Df}Wk_'
        'd1qJh&c=DSpG5Yr+dNM8?>1zMo*e};x29cLvF9L<D`&C)JV7uIYiqmH-Ug(HUU9gKq%9EZtW5v5#PDij_W;rH4iNcPwRwPc0!KHk'
        '$}QVz!_lYQ6gqJ9_0HgEUFr`BrQPdXJZ)%d%k3V3dZ7bQac|ysV@au6K5tcB2c=PN>2*Nq*E<8HIO&H(k=p7TecEnEX2p*mik;|r'
        'w5{(MqEA|Mr?YwQZE3~3#W9d(udqYId&mV#4?oY{_3+_CJ{;x4Fdr`S;SYSc$%jAj;SLRrCT@tSG?C*xLixFdQ5vl?v(hR$pUJlR'
        'rL*VG=kl$lX+p}mEwCbUn<&s)Rs@e$pLGn6Pak`H_X~-&PhnSM%};ro><?A>z79z9Tnx)3iGOs=(WlW|a!t~-5gMC_Hu#Sn6iBPk'
        '=^$RTQ*>!{)jCP)n;UhC%vGb1B;n>poub>TM$;sj-aNk!(H8m5lh*v^t9FRuyA9h-Pnr~e!lc<DI{ZDWNB;8aLFZ@uao;9}|4cLg'
        'BS$yT46f$*5sq~Shlpdx|INcSm}QpfrL$q5-+A9}w(4(Aveu)&bDP$w{i1bcV7Pf7J8fEmHf^kX<Fg{(Z8|47*}eIbB=cVeqiBHL'
        'G5`P'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
