# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/sebmar496/Desktop/leos/leos-S26-flight-computer/external/public_regulated_data_types/uavcan/si/sample/mass/Scalar.1.0.dsdl
#
# Generated at:  2026-04-03 14:48:41.803423 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.si.sample.mass.Scalar
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.time

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Scalar_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 timestamp: None | uavcan.time.SynchronizedTimestamp_1_0 = None,
                 kilogram:  None | int | float | _np_.float32 = None) -> None:
        """
        uavcan.si.sample.mass.Scalar.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param timestamp: uavcan.time.SynchronizedTimestamp.1.0 timestamp
        :param kilogram:  saturated float32 kilogram
        """
        self._timestamp: uavcan.time.SynchronizedTimestamp_1_0
        self._kilogram:  float

        if timestamp is None:
            self.timestamp = uavcan.time.SynchronizedTimestamp_1_0()
        elif isinstance(timestamp, uavcan.time.SynchronizedTimestamp_1_0):
            self.timestamp = timestamp
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 '
                             f'got {type(timestamp).__name__}')

        self.kilogram = kilogram if kilogram is not None else 0.0  # type: ignore

    @property
    def timestamp(self) -> uavcan.time.SynchronizedTimestamp_1_0:
        """
        uavcan.time.SynchronizedTimestamp.1.0 timestamp
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, x: uavcan.time.SynchronizedTimestamp_1_0) -> None:
        if isinstance(x, uavcan.time.SynchronizedTimestamp_1_0):
            self._timestamp = x
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 got {type(x).__name__}')

    @property
    def kilogram(self) -> float:
        """
        saturated float32 kilogram
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._kilogram

    @kilogram.setter
    def kilogram(self, x: int | float | _np_.float32) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._kilogram = x
        else:
            raise ValueError(f'kilogram: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.timestamp._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        if _np_.isfinite(self.kilogram):
            if self.kilogram > 340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(340282346638528859811704183484516925440.0)
            elif self.kilogram < -340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_aligned_f32(self.kilogram)
        else:
            _ser_.add_aligned_f32(self.kilogram)
        _ser_.pad_to_alignment(8)
        assert 88 <= (_ser_.current_bit_length - _base_offset_) <= 88, \
            'Bad serialization of uavcan.si.sample.mass.Scalar.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> Scalar_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "timestamp"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.time.SynchronizedTimestamp_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "kilogram"
        _f1_ = _des_.fetch_aligned_f32()
        self = Scalar_1_0(
            timestamp=_f0_,
            kilogram=_f1_)
        _des_.pad_to_alignment(8)
        assert 88 <= (_des_.consumed_bit_length - _base_offset_) <= 88, \
            'Bad deserialization of uavcan.si.sample.mass.Scalar.1.0'
        assert isinstance(self, Scalar_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'timestamp=%s' % self.timestamp,
            'kilogram=%s' % self.kilogram,
        ])
        return f'uavcan.si.sample.mass.Scalar.1.0({_o_0_})'

    _EXTENT_BYTES_ = 11

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8Nz>110{^{N-EQ5+5k8V7>(7?0$bWI1WSyqA)cWuwilr!N(<YJOrr26BEIU<;rtFejon46Jvb#%3CqRMvqJ~uvC;_uT9wCpA'
        'M+i_9Y3_nNLC`12ojXG=k0i&wYy{|hbM|NE+nL#!J%1hh=a;jc`mcC78$>3GJ>PIGSu8(cLCifrR7s|cw7e=#Zdjd%HrM>_Ami1e'
        'YVm&cmujIH_fwX@{H2`jge>)p^bAWf*qtzAyp52>OjpIEzr(eWDy>APnE1%ak19GsI}fV+RWai;Yqbn=%T4t$D1HW|;i{?_zbSbf'
        '9Z;F}BW9Uzk)IfC2E}-B*)g*+;oim|4TV;z{Den$VZc}*TZsuV)iMz$z`8i?w$DF{N2X;Wt=s_~^Y>CC`zeopom$@K`ly3u{6Jbi'
        '=4s!Gimn37kQwVIDgu_5igUMHMYzpdgSlHcg|7Kqb*C!M_`orZn2ruB+Rp<x+Dsxttqc!U8db%ZAE~g~{O@R|b60SZ=1IUcQCsBD'
        'DnqPbmI$`PNd^Jp5iv3iIWa2XglRCLnI4b?zNVJQ6xP=(tv8KI-8d*!TJ~XjL3-S~R<A+_lYkk%NTeYV-;&@Hl5yQ-Sr*HXS%|qu'
        'P)(R?je3S#&{A&rGz5wSoM`^%9AX38x3o$Qw3}i0YGnj+%yNB=7|!cOp#r@ogM-Sn52JcV!r5vnvbH`ArvP$0EY3Nyw2GvB2i*i8'
        'Td~@0_zmZmSGwR5vMVFt$wLMl-=3Z(q)V3mxV&=Iv#^{6Dz{{5X?2+lIMe1D*%dMrI0aWCwF8g5M^>)aIuGpy-Z|usCc7$+BQOLO'
        '2+7lwhuj#ZWjtsoKq3%n&5$j)4YmPWjL0%rwL;|vSJmcWI?6!>VPFju^F0avN-g9u3AHrRc+FwfV#oy<cGuopCkv^v<mQb<0-2D4'
        'FE!W;nTDjuGxXP+BpARYMT;35#ER81hCo3b@M_|B+fb1N>Gxr=5iE`|!kBLTn0M>tjfpLO;HZSdK$D|(7zap-s}|D&eV}nRg}@MS'
        'qVX!Y2(!iHno9AS*x|hs^Wr5ZU8bwz74a(V;C&KTo2xT%Z=J4x_}leLEEZRO&$W8ebe(SyH}uAKs&-SaDvtX#p{jVXEed=ugM`Ck'
        'cBCXs-l_AG#VsGPTui}{LmV|Qf78i$&pUMF0WdQ`9`IuRP#yGxK~r7v6bs^_ctdn^C@2vJqi~&gRP7hD{+8V1k&l7$WmK&fbG}iz'
        '4mnK3+|L-4i((cbmVxKT3QBTSOx=dUzIPiZA63PJ-aWW1re}DNFn#^4mEH|*wynx~F;}Mk=x!{nbhl#J7q*Li0SM|I--Ay$W-rSF'
        'xZ%F${X9lu2c_8bn)=&AhxVRYf4$ee*F5xRRad-uUoZo_u|oLn4p;jSr+=+CH34-K)Qt%RB|>Q^7#IgkZMgRg?zG)idb?X+8gs~I'
        '9oE_?B$E|KE+HsTao&`Px=I|_fiD714%ZMIuM((%ku!`b9VpNQ1*|R9^)=mrHA;6)#zVO!4_yW5A=@01>2w|2rpKnhylH#K8*f21'
        'N2XPA_URpq7w7B9`d0Z`DO>9@83Rv=UlqasKb%dd#{3|LbiUGFhl36UfwND3uZk1zOZ%Jp`vxE0)#8}1vZ^4@Qep;4pnwi!#x0&G'
        'SNlJNqQk7x2c7n~9}1{)mH4<gb(=-l0=~CM1US2%$M7l{JUJ_t|4}W_)zSp;Udb8_6`jljIA<bL?A{=-JrpLegM)KWDILLmosy0^'
        'Jcc-0(lPga9C4(i$KCjZ8=rJI<;JHGkC$}Dtv`V{S<;h;V<nw+>rWxhl=QTlpF<ok>2prcJmPaDJ%f0<q-POlOL`9RL`lyhPM7q8'
        '+yA_?d(qi>!Rfi=?7fKiLP=jjyjaqg5uYz9LA+4X%ZTSo`U>K?lKu$sY)M~5JX6viBhHufisN+^ajv8bj^85UsgnN0@%$;`$&y}k'
        'e7o+vp5xs^oGR&Sj{ob36D3`8=Xk^U<GMRf9oJ(eU2*4n)A@JRo$swC?(}VkKXdqVhwnK2g~MMueAnRz4mTYNhkFhmI{eh(XAVDi'
        '_=Ur-9e(TZy9RGfjyT~$D=f6aYAbxu3Y)DUT4Aph9=5`#t?*eZeBKIQw8Gb|@NFx6=Y$*{vC#OSU1A4wV*&OrXslEA;90#`bg(}U'
        'AJg#Oow^Ax27Ba*3=Nt<gI*F>AA;h9_2I3S<LmgHzt43J|2=;E*!9ZV(&V;`RUh6FU`YH2nx}XdwS6h(#5dxrT)e+8*4D)hsE7A|'
        'fc9o&uleEA!yi7q=7-PG&L-$SG8MOu6#7vk;bqb6g^G&1;k*0c#KoN-u%3&L#P6C)_y^$+3uZKw{6j_bEIhgJ4U#^!8W&SdF@_$F'
        'ZSASr{v={L0+CGMeU`$%0=xfShXHY@8WX6-+~A^3ShRVtD8|D4y<tp3?|%n6>?+z0000'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
