# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2026-04-18 00:09:03.894351 UTC
# Namespace:     leos.aggregate

from leos.aggregate.LowRate_0_1 import LowRate_0_1 as LowRate_0_1

# Convenience aliases of the newest minor versions known at the time of code generation.
LowRate_0 = LowRate_0_1
