# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/sebmar496/Desktop/leos-S26-flight-computer/external/leos_cyphal_types/leos/aggregate/1500.LowRate.0.1.dsdl
#
# Generated at:  2026-03-13 02:09:02.992678 UTC
# Is deprecated: no
# Fixed port ID: 1500
# Full name:     leos.aggregate.LowRate
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import leos.gps
import leos.sensors
import uavcan.time

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class LowRate_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 t_pkt:          None | uavcan.time.SynchronizedTimestamp_1_0 = None,
                 bme688:         None | leos.sensors.BME688_0_1 = None,
                 bme688_valid:   None | bool = None,
                 tsl2591:        None | leos.sensors.TSL2591_0_1 = None,
                 tsl2591_valid:  None | bool = None,
                 ltr390:         None | leos.sensors.LTR390_0_1 = None,
                 ltr390_valid:   None | bool = None,
                 pmsa003i:       None | leos.sensors.PMSA003I_0_1 = None,
                 pmsa003i_valid: None | bool = None,
                 gps_data:       None | leos.gps.Fix_0_1 = None) -> None:
        """
        leos.aggregate.LowRate.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param t_pkt:          uavcan.time.SynchronizedTimestamp.1.0 t_pkt
        :param bme688:         leos.sensors.BME688.0.1 bme688
        :param bme688_valid:   bool bme688_valid
        :param tsl2591:        leos.sensors.TSL2591.0.1 tsl2591
        :param tsl2591_valid:  bool tsl2591_valid
        :param ltr390:         leos.sensors.LTR390.0.1 ltr390
        :param ltr390_valid:   bool ltr390_valid
        :param pmsa003i:       leos.sensors.PMSA003I.0.1 pmsa003i
        :param pmsa003i_valid: bool pmsa003i_valid
        :param gps_data:       leos.gps.Fix.0.1 gps_data
        """
        self._t_pkt:          uavcan.time.SynchronizedTimestamp_1_0
        self._bme688:         leos.sensors.BME688_0_1
        self._bme688_valid:   bool
        self._tsl2591:        leos.sensors.TSL2591_0_1
        self._tsl2591_valid:  bool
        self._ltr390:         leos.sensors.LTR390_0_1
        self._ltr390_valid:   bool
        self._pmsa003i:       leos.sensors.PMSA003I_0_1
        self._pmsa003i_valid: bool
        self._gps_data:       leos.gps.Fix_0_1

        if t_pkt is None:
            self.t_pkt = uavcan.time.SynchronizedTimestamp_1_0()
        elif isinstance(t_pkt, uavcan.time.SynchronizedTimestamp_1_0):
            self.t_pkt = t_pkt
        else:
            raise ValueError(f't_pkt: expected uavcan.time.SynchronizedTimestamp_1_0 '
                             f'got {type(t_pkt).__name__}')

        if bme688 is None:
            self.bme688 = leos.sensors.BME688_0_1()
        elif isinstance(bme688, leos.sensors.BME688_0_1):
            self.bme688 = bme688
        else:
            raise ValueError(f'bme688: expected leos.sensors.BME688_0_1 '
                             f'got {type(bme688).__name__}')

        self.bme688_valid = bme688_valid if bme688_valid is not None else False

        if tsl2591 is None:
            self.tsl2591 = leos.sensors.TSL2591_0_1()
        elif isinstance(tsl2591, leos.sensors.TSL2591_0_1):
            self.tsl2591 = tsl2591
        else:
            raise ValueError(f'tsl2591: expected leos.sensors.TSL2591_0_1 '
                             f'got {type(tsl2591).__name__}')

        self.tsl2591_valid = tsl2591_valid if tsl2591_valid is not None else False

        if ltr390 is None:
            self.ltr390 = leos.sensors.LTR390_0_1()
        elif isinstance(ltr390, leos.sensors.LTR390_0_1):
            self.ltr390 = ltr390
        else:
            raise ValueError(f'ltr390: expected leos.sensors.LTR390_0_1 '
                             f'got {type(ltr390).__name__}')

        self.ltr390_valid = ltr390_valid if ltr390_valid is not None else False

        if pmsa003i is None:
            self.pmsa003i = leos.sensors.PMSA003I_0_1()
        elif isinstance(pmsa003i, leos.sensors.PMSA003I_0_1):
            self.pmsa003i = pmsa003i
        else:
            raise ValueError(f'pmsa003i: expected leos.sensors.PMSA003I_0_1 '
                             f'got {type(pmsa003i).__name__}')

        self.pmsa003i_valid = pmsa003i_valid if pmsa003i_valid is not None else False

        if gps_data is None:
            self.gps_data = leos.gps.Fix_0_1()
        elif isinstance(gps_data, leos.gps.Fix_0_1):
            self.gps_data = gps_data
        else:
            raise ValueError(f'gps_data: expected leos.gps.Fix_0_1 '
                             f'got {type(gps_data).__name__}')

    @property
    def t_pkt(self) -> uavcan.time.SynchronizedTimestamp_1_0:
        """
        uavcan.time.SynchronizedTimestamp.1.0 t_pkt
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._t_pkt

    @t_pkt.setter
    def t_pkt(self, x: uavcan.time.SynchronizedTimestamp_1_0) -> None:
        if isinstance(x, uavcan.time.SynchronizedTimestamp_1_0):
            self._t_pkt = x
        else:
            raise ValueError(f't_pkt: expected uavcan.time.SynchronizedTimestamp_1_0 got {type(x).__name__}')

    @property
    def bme688(self) -> leos.sensors.BME688_0_1:
        """
        leos.sensors.BME688.0.1 bme688
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._bme688

    @bme688.setter
    def bme688(self, x: leos.sensors.BME688_0_1) -> None:
        if isinstance(x, leos.sensors.BME688_0_1):
            self._bme688 = x
        else:
            raise ValueError(f'bme688: expected leos.sensors.BME688_0_1 got {type(x).__name__}')

    @property
    def bme688_valid(self) -> bool:
        """
        bool bme688_valid
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._bme688_valid

    @bme688_valid.setter
    def bme688_valid(self, x: bool) -> None:
        self._bme688_valid = bool(x)  # Cast to bool implements saturation

    @property
    def tsl2591(self) -> leos.sensors.TSL2591_0_1:
        """
        leos.sensors.TSL2591.0.1 tsl2591
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._tsl2591

    @tsl2591.setter
    def tsl2591(self, x: leos.sensors.TSL2591_0_1) -> None:
        if isinstance(x, leos.sensors.TSL2591_0_1):
            self._tsl2591 = x
        else:
            raise ValueError(f'tsl2591: expected leos.sensors.TSL2591_0_1 got {type(x).__name__}')

    @property
    def tsl2591_valid(self) -> bool:
        """
        bool tsl2591_valid
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._tsl2591_valid

    @tsl2591_valid.setter
    def tsl2591_valid(self, x: bool) -> None:
        self._tsl2591_valid = bool(x)  # Cast to bool implements saturation

    @property
    def ltr390(self) -> leos.sensors.LTR390_0_1:
        """
        leos.sensors.LTR390.0.1 ltr390
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._ltr390

    @ltr390.setter
    def ltr390(self, x: leos.sensors.LTR390_0_1) -> None:
        if isinstance(x, leos.sensors.LTR390_0_1):
            self._ltr390 = x
        else:
            raise ValueError(f'ltr390: expected leos.sensors.LTR390_0_1 got {type(x).__name__}')

    @property
    def ltr390_valid(self) -> bool:
        """
        bool ltr390_valid
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._ltr390_valid

    @ltr390_valid.setter
    def ltr390_valid(self, x: bool) -> None:
        self._ltr390_valid = bool(x)  # Cast to bool implements saturation

    @property
    def pmsa003i(self) -> leos.sensors.PMSA003I_0_1:
        """
        leos.sensors.PMSA003I.0.1 pmsa003i
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._pmsa003i

    @pmsa003i.setter
    def pmsa003i(self, x: leos.sensors.PMSA003I_0_1) -> None:
        if isinstance(x, leos.sensors.PMSA003I_0_1):
            self._pmsa003i = x
        else:
            raise ValueError(f'pmsa003i: expected leos.sensors.PMSA003I_0_1 got {type(x).__name__}')

    @property
    def pmsa003i_valid(self) -> bool:
        """
        bool pmsa003i_valid
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._pmsa003i_valid

    @pmsa003i_valid.setter
    def pmsa003i_valid(self, x: bool) -> None:
        self._pmsa003i_valid = bool(x)  # Cast to bool implements saturation

    @property
    def gps_data(self) -> leos.gps.Fix_0_1:
        """
        leos.gps.Fix.0.1 gps_data
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._gps_data

    @gps_data.setter
    def gps_data(self, x: leos.gps.Fix_0_1) -> None:
        if isinstance(x, leos.gps.Fix_0_1):
            self._gps_data = x
        else:
            raise ValueError(f'gps_data: expected leos.gps.Fix_0_1 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.t_pkt._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        # Delimited serialization of leos.sensors.BME688.0.1, extent 3200, max bit length 2256
        _nested_ = _ser_.fork_bytes(286)  # Also includes the length of the delimiter header.
        _nested_.skip_bits(32)  # Leave space for the delimiter header.
        assert _nested_.current_bit_length == 32
        self.bme688._serialize_(_nested_)
        _nested_length_ = _nested_.current_bit_length - 32
        del _nested_
        assert 208 <= _nested_length_ <= 2256
        assert _nested_length_ % 8 == 0
        _ser_.add_aligned_u32(_nested_length_ // 8)  # Jump back and serialize the delimiter header.
        _ser_.skip_bits(_nested_length_)             # Return to the current offset.
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.add_unaligned_bit(self.bme688_valid)
        _ser_.pad_to_alignment(8)
        # Delimited serialization of leos.sensors.TSL2591.0.1, extent 2400, max bit length 2128
        _nested_ = _ser_.fork_bytes(270)  # Also includes the length of the delimiter header.
        _nested_.skip_bits(32)  # Leave space for the delimiter header.
        assert _nested_.current_bit_length == 32
        self.tsl2591._serialize_(_nested_)
        _nested_length_ = _nested_.current_bit_length - 32
        del _nested_
        assert 80 <= _nested_length_ <= 2128
        assert _nested_length_ % 8 == 0
        _ser_.add_aligned_u32(_nested_length_ // 8)  # Jump back and serialize the delimiter header.
        _ser_.skip_bits(_nested_length_)             # Return to the current offset.
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.add_unaligned_bit(self.tsl2591_valid)
        _ser_.pad_to_alignment(8)
        # Delimited serialization of leos.sensors.LTR390.0.1, extent 2400, max bit length 2112
        _nested_ = _ser_.fork_bytes(268)  # Also includes the length of the delimiter header.
        _nested_.skip_bits(32)  # Leave space for the delimiter header.
        assert _nested_.current_bit_length == 32
        self.ltr390._serialize_(_nested_)
        _nested_length_ = _nested_.current_bit_length - 32
        del _nested_
        assert 64 <= _nested_length_ <= 2112
        assert _nested_length_ % 8 == 0
        _ser_.add_aligned_u32(_nested_length_ // 8)  # Jump back and serialize the delimiter header.
        _ser_.skip_bits(_nested_length_)             # Return to the current offset.
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.add_unaligned_bit(self.ltr390_valid)
        _ser_.pad_to_alignment(8)
        # Delimited serialization of leos.sensors.PMSA003I.0.1, extent 2400, max bit length 2256
        _nested_ = _ser_.fork_bytes(286)  # Also includes the length of the delimiter header.
        _nested_.skip_bits(32)  # Leave space for the delimiter header.
        assert _nested_.current_bit_length == 32
        self.pmsa003i._serialize_(_nested_)
        _nested_length_ = _nested_.current_bit_length - 32
        del _nested_
        assert 208 <= _nested_length_ <= 2256
        assert _nested_length_ % 8 == 0
        _ser_.add_aligned_u32(_nested_length_ // 8)  # Jump back and serialize the delimiter header.
        _ser_.skip_bits(_nested_length_)             # Return to the current offset.
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.add_unaligned_bit(self.pmsa003i_valid)
        _ser_.pad_to_alignment(8)
        # Delimited serialization of leos.gps.Fix.0.1, fixed bit length 304 (38 bytes)
        _ser_.add_aligned_u32(38)  # Delimiter header is constant in this case.
        _ser_base_offset_ = _ser_.current_bit_length
        self.gps_data._serialize_(_ser_)
        assert _ser_.current_bit_length - _ser_base_offset_ == 304
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 248 <= (_ser_.current_bit_length - _base_offset_) <= 13048, \
            'Bad serialization of leos.aggregate.LowRate.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> LowRate_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "t_pkt"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.time.SynchronizedTimestamp_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "bme688"
        _des_.pad_to_alignment(8)
        # Delimited deserialization of leos.sensors.BME688.0.1, extent 3200
        _dh_ = _des_.fetch_aligned_u32()  # Read the delimiter header.
        if _dh_ * 8 > _des_.remaining_bit_length:
            raise _des_.FormatError(f'Delimiter header specifies {_dh_ * 8} bits, '
                                    f'but the remaining length is only {_des_.remaining_bit_length} bits')
        _nested_ = _des_.fork_bytes(_dh_)
        _des_.skip_bits(_dh_ * 8)
        _f1_ = leos.sensors.BME688_0_1._deserialize_(_nested_)
        del _nested_
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f2_ holds the value of "bme688_valid"
        _f2_ = _des_.fetch_unaligned_bit()
        # Temporary _f3_ holds the value of "tsl2591"
        _des_.pad_to_alignment(8)
        # Delimited deserialization of leos.sensors.TSL2591.0.1, extent 2400
        _dh_ = _des_.fetch_aligned_u32()  # Read the delimiter header.
        if _dh_ * 8 > _des_.remaining_bit_length:
            raise _des_.FormatError(f'Delimiter header specifies {_dh_ * 8} bits, '
                                    f'but the remaining length is only {_des_.remaining_bit_length} bits')
        _nested_ = _des_.fork_bytes(_dh_)
        _des_.skip_bits(_dh_ * 8)
        _f3_ = leos.sensors.TSL2591_0_1._deserialize_(_nested_)
        del _nested_
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f4_ holds the value of "tsl2591_valid"
        _f4_ = _des_.fetch_unaligned_bit()
        # Temporary _f5_ holds the value of "ltr390"
        _des_.pad_to_alignment(8)
        # Delimited deserialization of leos.sensors.LTR390.0.1, extent 2400
        _dh_ = _des_.fetch_aligned_u32()  # Read the delimiter header.
        if _dh_ * 8 > _des_.remaining_bit_length:
            raise _des_.FormatError(f'Delimiter header specifies {_dh_ * 8} bits, '
                                    f'but the remaining length is only {_des_.remaining_bit_length} bits')
        _nested_ = _des_.fork_bytes(_dh_)
        _des_.skip_bits(_dh_ * 8)
        _f5_ = leos.sensors.LTR390_0_1._deserialize_(_nested_)
        del _nested_
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f6_ holds the value of "ltr390_valid"
        _f6_ = _des_.fetch_unaligned_bit()
        # Temporary _f7_ holds the value of "pmsa003i"
        _des_.pad_to_alignment(8)
        # Delimited deserialization of leos.sensors.PMSA003I.0.1, extent 2400
        _dh_ = _des_.fetch_aligned_u32()  # Read the delimiter header.
        if _dh_ * 8 > _des_.remaining_bit_length:
            raise _des_.FormatError(f'Delimiter header specifies {_dh_ * 8} bits, '
                                    f'but the remaining length is only {_des_.remaining_bit_length} bits')
        _nested_ = _des_.fork_bytes(_dh_)
        _des_.skip_bits(_dh_ * 8)
        _f7_ = leos.sensors.PMSA003I_0_1._deserialize_(_nested_)
        del _nested_
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f8_ holds the value of "pmsa003i_valid"
        _f8_ = _des_.fetch_unaligned_bit()
        # Temporary _f9_ holds the value of "gps_data"
        _des_.pad_to_alignment(8)
        # Delimited deserialization of leos.gps.Fix.0.1, extent 2400
        _dh_ = _des_.fetch_aligned_u32()  # Read the delimiter header.
        if _dh_ * 8 > _des_.remaining_bit_length:
            raise _des_.FormatError(f'Delimiter header specifies {_dh_ * 8} bits, '
                                    f'but the remaining length is only {_des_.remaining_bit_length} bits')
        _nested_ = _des_.fork_bytes(_dh_)
        _des_.skip_bits(_dh_ * 8)
        _f9_ = leos.gps.Fix_0_1._deserialize_(_nested_)
        del _nested_
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = LowRate_0_1(
            t_pkt=_f0_,
            bme688=_f1_,
            bme688_valid=_f2_,
            tsl2591=_f3_,
            tsl2591_valid=_f4_,
            ltr390=_f5_,
            ltr390_valid=_f6_,
            pmsa003i=_f7_,
            pmsa003i_valid=_f8_,
            gps_data=_f9_)
        _des_.pad_to_alignment(8)
        assert 248 <= (_des_.consumed_bit_length - _base_offset_) <= 13048, \
            'Bad deserialization of leos.aggregate.LowRate.0.1'
        assert isinstance(self, LowRate_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            't_pkt=%s' % self.t_pkt,
            'bme688=%s' % self.bme688,
            'bme688_valid=%s' % self.bme688_valid,
            'tsl2591=%s' % self.tsl2591,
            'tsl2591_valid=%s' % self.tsl2591_valid,
            'ltr390=%s' % self.ltr390,
            'ltr390_valid=%s' % self.ltr390_valid,
            'pmsa003i=%s' % self.pmsa003i,
            'pmsa003i_valid=%s' % self.pmsa003i_valid,
            'gps_data=%s' % self.gps_data,
        ])
        return f'leos.aggregate.LowRate.0.1({_o_0_})'

    _FIXED_PORT_ID_ = 1500
    _EXTENT_BYTES_ = 2048

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
        'ABzY8zj3o^0{`t?Yiu0Xb>4aGgA^svmL<{gL!;QSsaRYtsfQ`YPAJQf>0TY0(Zi<G+RNG9OU^83ch)nr6d5!zg`f>>Y|#O{1@xzY'
        'f}(-?Cs5J;P}@HWTC@U^0_w|Pnl@01{*a3nkn@Wu3b^OY?9M((krGK+HVNo(c<(*;oO|!N-#KS=cIV|kc=GL#_fy(en9JB1Bc8Om'
        'rK^Vi9W`a}crtC~3Z|_)yj<G;3ODo|K4#9&6?pl>@_`HG@0NQ@k))o_bE~X{O54vkRx#}qE#5dJoXo2^oMMl`O*^hmO<8<Ob$I-g'
        'dH%FYbH|c1+_H5uPqReds62mIW+5j0ZuvsFv@NMRj-{uH4!6s1<CM$j8;mNK!Y6fZWNJ!uCNrv|CLPjDi~5aPXK8;?ok^?txTEKI'
        '{LEZFtyyMX{|>Ga8*E3-70Ozdwu1>QM4D(1p>%C`g}rAvJqi|Wl|F-d>^hgX^{G71yq0(P6t^0;W?M3)J4u7*ryQ-!hEU72YCFlC'
        'nL#c0m-dWRCnC1^3G4&v!mSa0r+m6xdL)TD<}<35sh{ZmVhWeGEvKg~)8=V2pDCB*WX4RF$Nx(Vh0bbR$rp1eZYk!ZQa8$098Gl;'
        'O`YLNLA7n3QEWY*=8A3RxT0Dp!cwg{C5M0J9YxRMcyFW=@1#j9?Kr7v=~LL<tH*i#pf`#(SV^fiKcMKglHrp&?uk<1R-alZ7<yWD'
        '@XX^1O_MHK7R?i|kffr`JMo~D6jv<%ZV}H0*(WVCSDW1qj?bG+$)RH0I;hy3dxO#@&TAKNp?ZD_Tdf%#*XF6Bd(t~`6{y^dY7{wX'
        '>6l8M&(Jm@nKaDvzJ5Xfk)wUMCCYg{gL?9`iaNf~*{LXf%HTUkjyCQr4p&oV(NP8mhmI(7T(#_j%6UysYt&W1lXK?c%5mlBVQ<bl'
        'UevpYwqq&h&7zS(K`22{ig@eN+_qIqH|Bg5&=3^eu>);!+mH>lr4u=VQXS1K+BC`&kKLIfPNAqM4JYQaI__8AK|5B`mTv2I++WNI'
        '18qT1_nkOCs`TbfM>+Y*0R=4~k9%pMytHbeQ4|ZbU(YM4IlQDKv7pWwrs|zB9uy)#+*AB)^{A8_sXv8-ZA~={I$<)mDTDWU!+jBx'
        'ytYv}jt#zzI>9-hQ9SFAS<oI>)SJhHQE(IOco{Fku2SrTnWt;w1ouws(VnV2J;R2yXSD+?ME6NM=wF@axluOy`kSL=Ena%&+uSmn'
        'MSJ#!=SI6Roj1?t<7GrbPoZ+@i7F`Y*#a6Ifms72#7=wmsTx&%v=>Spxa2go+Sq@x@*F_m>9U<Frg&*r9S$Z_b3U%pD*Cj2+K@I_'
        'L_o=K6pGi0XUgxFb|feDS)NJKK_&G}d9?IU(l(1$nq!B-lLZywqO^m48G0(7G|V)rRq7Z+)Sn%r&JW9_3;pNtve^ALPvunW@Uf%)'
        'uW)<XF$?_!=zV7fkM>O(`jqDMk-tFQtbRU=6j#_^D5mgoClT?B2I*8oVY}al-hSH4{<hE?ABZR7w3THK>~<wJ)kc*G9FmpmTYevp'
        '=%=GT9MIef%}ut1=wMoi6?6n-)p+Gqyw1*f)0*z{?u%U~(>qa5DB6*uHQYa(z%+_JLU;gClY@U~xN^LKxaVdL;V)AWOxBz-aVEsB'
        'Dn@%ZbOy(mR-awqX?;?!y9MYzra9VCw|A_*@6Ds;zQ>FByM;hbnwCqu+dC^>+Up%^(lL{kX*%9qc0t9R(oU7$-q4fuPf1Ru3^d|r'
        's+XYVm+;J-=D*9Ou9tP^l=t@;9^BB9lr#(FlCs<+_FOJyqB>|4z;k8=@n1)%Q61B&k51AWVp~~Dm3EG)83O*6LE04cjus6AeOq&{'
        '_QLO%d)bg{r!Yz>_%oDQteC=e=JY)IY<y5>=^;vf8#jma@1)C*kU_V2w3wpni?|YYl7(r9P$fjr6vPplSa}N9g(kbaa0zYKHZ42;'
        'GJNys(2yUDRKlXBV5APx6oj<rwSx<u&{)c(_#kJaTy3^NY)#nSN*olxR2+jjT5EIkQy2U^woDLaS?XN5wD%2kP1NEa?r~~u41TsJ'
        'xxp!7s6=Ho{bPatr4EdU(0p}gt_&fe^l;S-CMmpYVeCf6=lq5LruL41f~uCOJLui$3<w?bZ7qhxk-;Fu(5=&Qbw<#QM$j<T-qUJ+'
        'il62M?&!;z-?V2Os5x@fPZo1MldxDwvmq4I930LB>Iu0_to)X|-?;mt%j8O1IA~)MlU)|^{}$;v+R(?sEaI|Qg|DNfk3~@n)*0|)'
        '3;w;W?KsxKI$hS~_r*xo_GQPhZLG^>I~wN2R&3k3A`jcncDSs&BEw}5-ElPAiHE`-ZjppN*uHC3{Olq2u*)9t$I95>MZCLL&C7PN'
        'M_jh2tq$0WeS6n57u(JDxU8qT)2Pd%YvyNrS&z%Uw5(1z0{b7kt9jX@>`N|tykWnv7w3E8uIFQqvBzEZ<cj*@C>*ozo@B5m*pn_('
        'g1sfJ_uuo3Y#&ox_GNz_WhMPd`cvy7kL_n)cG=TanRVwtyY!WHlfj;1PrK}yJDv=3C^#C&KD(~6*;m*zF6*tXvvOt!)?EgBmi4;q'
        'tE*loa^U#qHbf70fPK|v2Ww~hG|t&uf4+SiCYL?O4!SJ9rhPyz<mul~omd}>yDU+&gI?bf1~yzO>t_j<4X$}dkQ4b1ZHj(ufDO9r'
        'aI3`}#JLkyt2wf1y0Am+u*;6#)t(_Y@;<+*y0RnesLO^Ltt&zHb!^l1V9#T=!CtuQy~7!h|7-U}Z+48m;IbE&x5L9IV~A|=rTeBI'
        '`x<-EWnaIi{l!^uj&I!8HL#c1*IhQ;VzYSqMQz4whL8v$8A1_EFjx#?BE)1^3PUWyx}jTyZW+2GtOt5T=#il(0!vY*fFgn-gA!rA'
        '&?`c(480MSfP@GM84?jT1VbVW$uJaQ!!RtuunfZyHUc9ejL0w&VPh~R!k7$W5jGCvB8<y09$^zOA;N?V6A`9?CW0n|7GVV_h)|HB'
        '5Mi@0E5fV{vk^8A^CHa4FdtzHupq*M3=0wFf-8b6gBxKN;i3o^Ww;n&m*A2Jmt?pUVVB{u2$yBJ9AQ`BiU?O^xDsJk;i?E%Ww;t)'
        '*Wj86*JQXBVb|fh2-jt}9$`1&h6p!gxDjECuqeW!42uzV6K;xdQ-+%nb_;Haa7%_;5q2AHi*Q?p+Yz<|OCl`ce&X&55RxDihENn@'
        '0>mVU;U-6+TYzo}y2H>Ng&qNVB<Kl4PZSgZ6bY0tC{gGYpjU$4F!V+tAwWWcL>LlL7!qJef}t=BMPXQgVF`xAFdT&u0Y)Sk3ByPf'
        '#snCXU@Qz{Q5Y9sT!Qg1j7MQYfC&jE!Y~m9O#n>-Eeu)|3IY@)D1@O9g;@b+C72DvY!v1Nn3rHa4D(S~5MV)qg)l5c!4<%jzzu^N'
        'g^L1Ql;C0*E=J*!0GA}V6oyMtxGcbB2`-1>auluza7BVEVYm{7s{&k=;A$AIM&X(O*Ce<WhHFu{F2HpOu7}}z6mAG`LxLM&xDka#'
        '0Tv}#l3+0mi&3~Kz)cBmhT&!uZV7Npf?Hv@6@}XZ+?L>W7;Z;lNpOoPZc`H7jY)L(gOo(aD0$jSqBkLl?)LX#D~aBKBpO3-e|Oh4'
        'iB|69m^UDaRvORYbDKmfwHF^>m?WCk{4~zo+jzcT=p>r<q_=7bTS;_N65VJqTS@d<lV~4hda<v2D~Y~`B--~%TS@e0B+)fQtWTor'
        'Q)tYaAr`CV&|)Qrj$q<JnKUKQUNSA;&omm-XUwB1nU>q9(Ud+{GU=@}`tzDb`#Cfw)2mLStMv(f1(RPVplaXzZaI5Q2!%A))?R&I'
        '8yVGJ(@vGnZ)`bGP=V0zS0FSN0cm4Y@bkfO<=okmLw!7-HmTso_C`|CnS-L@ooBqNMJm*)^yqf25(vkuRP>ga%d0s(t$6hc#OqbA'
        '9aMCuTG^E^8b%*#p40QBY+N~|Pjh8VwbQCmnK@q8PB)b2bkr4kMJhEETzhkKif`H%J?O#HCGB0RU1@k@qRrImQ({#A<yD@wl#1*x'
        'b(}Oz)oCc<s4F!obtZG_R9<(ARJ!`|2M>kne?I;6(@G(mFGnlp^bFN>tWc8jWThm<*5gH-H}2Ka6)he=gWIoKD^#XrzlBEIqG9$d'
        'nerVpixj-mZMXuH$d{c!Qhy7+x3Rat*86GE{nbVH`-^UK8MN6Z3lwd=T#|{qT#8ls$r$}@`^*?)eL0LmwKY}SR5Tm^HJfIzk`+v5'
        'f0M~LJm=NqY`E1-b7Mx&H(1T@k=6X5$!acaj@8ty`z{S<Tip~7yzMkBW(D(kyvcn0QnL-UoN$gi^y!H@!})VEoF6wC&Tnsy;rJ`Q'
        'OPh&QK7R1PLyc-U6+hNwEBA2FJEl|{*J0~a44ke`&FRE@wI68T&jL-dkbRR*f0W4gh>R2YV<PVn`5BQP5&0(~e~+Z-SqaAGo}J|H'
        'VY6vOGCfz&RHL%R)Y4z6K<ytGObk`ZP|+?1maz<(c*><{g$s?LQn~6I!?)I5zf~DPt?iHeVLzhk&M(HuRT_VG1dYl6@3aI4hlyHn'
        'hzvrpU3>G)KKB@o8f)P8#Wl5OX99Tz>?yS2Xll>?VZh;HkK2Z$sXhBQ0ml{Wxzc7$&F$^ibOT4-Xd|zw-3JiuJ#-Zp{OauQ<CPu_'
        'F7kW9^`)D;-j_f7FWB-Kxsau3l7{7-GR$|C_9QcvPY+s2jjI{_)m*u)+@W&2-pX4nx;E^`m8U<&w0otJ>-jD^wCaEC+TQ8;M~$}v'
        'F16{cIEP3o$Gt-Q)&yzW%cf~?HQ$^f3BI53KU&n~^V4UA^i1n4?LG+bNW%vK&Yn3nc;wi?I)4)2gB7#Cd+>W5p7A7&;%tM<%T9}E'
        '!c#=@L<}NDBBmIa^<Vft&D>C*cC5OiYjJAP>M4BgyxM2fTllvxn?~c%y0V;pk<I%SWK`{D&9;?2FRlhMH|MysFQPIq(UE<LmbZb>'
        'cyL8%oak5y8s|Hfg~q638$L8O!^c}<9egyv;r0s8TJW&(gHfl>o<4Lev8iy_^ns&bLa8{TH=^9XlGS}g<ll+>g2;am`DM)#|8f%|'
        '_kl!ZpVkz)SGINw<L(OMx&w?G#!<s<Fs`Y+f^q-oW86On823?NI=`%8-0CeW`=6`AxJ^0j2OZ)fhGThXvwDQ<@>$jbaJw4-ZVb*G'
        'Pb3b#cE2F5al%4wAd%$xnYC~X9$6Dd2gz8QkZtO_deReAv{%j4<uj42fU9!5UX}1BognfXL`I0bPJ|ITOJt15TSU$gd56fiiKK}n'
        'rQjC+m5=X*4aN6?z)aSH@Ug(Qw%*QsVc*UO?c(iaxLe=U2<_g~EW_RU)<$Ue)@B**O?-os{f6ZE;Nw!&2cHOFfCZQTTyW*-wr?16'
        'WVy5&|Gi0f`9b&K=#Fd^w@F`%58qK`T8kI&^1S#|!H%EQXIFCGD+rEE>a$66`VKE-hMQi<TnOE-pQTT|pZXU-lA$^ew*Kq;LM*Hr'
        'PBOQyuh{GY=NRM_>~)>hvDEZ*GQ+1<3aDZYft#&5c9On(XVolS9?Ohw>nWqn|II#1uNCkLC5ukFF+vN;h?W0GfElGHfyfRbF(SK('
        '>?HCykv&A7BJu>0ULsEu=_7K0NP<XQ4zTx;uotyWt$);p%jq9Dlt>UPv<cQq{ME5D3f_DFYlgi40kt)rQBrfkS5Ni%Uu{<X4zqZt'
        '_homslG82Aw7g+CJ+J3f!<)#ielMT@g=wfjrdqdDaU&A8Atj*NiUdEW(WT%=mwwPBV00<8kC}#pnCUnUI^G&^H8r>Ay?}!*wDLAJ'
        'w~y6+h=YFE%G=c3p7$p>=qIhbP0j6je}#j7)ymt{+#HkmydUGBk6U@0n%nb!f`dM34NaG@d8yXSy}^(WD9#sJhPQN7LfIuhl>Ofz'
        'l=VPU2%vIj0FX}vuy~*fhMNku*+IE3(9IsfzwQf2J@6qeIZSdMjYTHswLRH$w4%A}Z_$gwH;DW#k++Hbl*r!^IYbBjGkO}Lr^7`4'
        'o5(RDpAh*UA|KHy{<@Z~{G0DG-(7!~8GL7K|G*J+oRu$*ZRb1>V_%<zor<3rDFJJpCpD=$xZwFu`hveEU)T|_V0u;kj@m7+_=OzF'
        '127&!FdnMCj(J(EzK$8k%edIpiu}#(&92zzehWwaysH)aC$Rlytv&l^fxLNwhCQwFn%mpUL;nlvo>qAa*sj&uvx-!ecNu$b?Q50S'
        '+}>W^pWvvE_qEESmo~R+?b)9P^5}(3;Xtdr=JxjT{sBk5d!SX`BDT-g+OvNxSLLCXg{8r^-nYKJQrfc(^Z0H*f8T>Z`bGes9&&o1'
        'c{qSd4<&ycyc^mq1kNrt_|ac9`_at@INzg&hBw@!hGHvz&*Jb(9#t7`?@{Cb4=stACMjJ200'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
