# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/sebmar496/Desktop/leos/leos-S26-flight-computer/external/public_regulated_data_types/uavcan/pnp/cluster/390.AppendEntries.1.0.dsdl
#
# Generated at:  2026-04-03 14:48:41.969501 UTC
# Is deprecated: no
# Fixed port ID: 390
# Full name:     uavcan.pnp.cluster.AppendEntries
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.pnp.cluster

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class AppendEntries_1_0:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        DEFAULT_MIN_ELECTION_TIMEOUT: int = 2
        DEFAULT_MAX_ELECTION_TIMEOUT: int = 4

        def __init__(self,
                     term:           None | int | _np_.uint32 = None,
                     prev_log_term:  None | int | _np_.uint32 = None,
                     prev_log_index: None | int | _np_.uint16 = None,
                     leader_commit:  None | int | _np_.uint16 = None,
                     entries:        None | _NDArray_[_np_.object_] | list[uavcan.pnp.cluster.Entry_1_0] = None) -> None:
            """
            uavcan.pnp.cluster.AppendEntries.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param term:           saturated uint32 term
            :param prev_log_term:  saturated uint32 prev_log_term
            :param prev_log_index: saturated uint16 prev_log_index
            :param leader_commit:  saturated uint16 leader_commit
            :param entries:        uavcan.pnp.cluster.Entry.1.0[<=1] entries
            """
            self._term:           int
            self._prev_log_term:  int
            self._prev_log_index: int
            self._leader_commit:  int
            self._entries:        _NDArray_[_np_.object_]

            self.term = term if term is not None else 0  # type: ignore

            self.prev_log_term = prev_log_term if prev_log_term is not None else 0  # type: ignore

            self.prev_log_index = prev_log_index if prev_log_index is not None else 0  # type: ignore

            self.leader_commit = leader_commit if leader_commit is not None else 0  # type: ignore

            if entries is None:
                self.entries = _np_.array([], _np_.object_)
            else:
                if isinstance(entries, _np_.ndarray) and entries.dtype == _np_.object_ and entries.ndim == 1 and entries.size <= 1:  # type: ignore
                    # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                    self._entries = entries
                else:
                    # Last resort, slow construction of a new array. New memory may be allocated.
                    entries = _np_.array(entries, _np_.object_).flatten()
                    if not entries.size <= 1:  # Length cannot be checked before casting and flattening
                        raise ValueError(f'entries: invalid array length: not {entries.size} <= 1')
                    self._entries = entries
                assert isinstance(self._entries, _np_.ndarray)
                assert self._entries.dtype == _np_.object_  # type: ignore
                assert self._entries.ndim == 1
                assert len(self._entries) <= 1

        @property
        def term(self) -> int:
            """
            saturated uint32 term
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._term

        @term.setter
        def term(self, x: int | _np_.uint32) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 4294967295:
                self._term = x
            else:
                raise ValueError(f'term: value {x} is not in [0, 4294967295]')

        @property
        def prev_log_term(self) -> int:
            """
            saturated uint32 prev_log_term
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._prev_log_term

        @prev_log_term.setter
        def prev_log_term(self, x: int | _np_.uint32) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 4294967295:
                self._prev_log_term = x
            else:
                raise ValueError(f'prev_log_term: value {x} is not in [0, 4294967295]')

        @property
        def prev_log_index(self) -> int:
            """
            saturated uint16 prev_log_index
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._prev_log_index

        @prev_log_index.setter
        def prev_log_index(self, x: int | _np_.uint16) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 65535:
                self._prev_log_index = x
            else:
                raise ValueError(f'prev_log_index: value {x} is not in [0, 65535]')

        @property
        def leader_commit(self) -> int:
            """
            saturated uint16 leader_commit
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._leader_commit

        @leader_commit.setter
        def leader_commit(self, x: int | _np_.uint16) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 65535:
                self._leader_commit = x
            else:
                raise ValueError(f'leader_commit: value {x} is not in [0, 65535]')

        @property
        def entries(self) -> _NDArray_[_np_.object_]:
            """
            uavcan.pnp.cluster.Entry.1.0[<=1] entries
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._entries

        @entries.setter
        def entries(self, x: _NDArray_[_np_.object_] | list[uavcan.pnp.cluster.Entry_1_0]) -> None:
            if isinstance(x, _np_.ndarray) and x.dtype == _np_.object_ and x.ndim == 1 and x.size <= 1:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._entries = x
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                x = _np_.array(x, _np_.object_).flatten()
                if not x.size <= 1:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'entries: invalid array length: not {x.size} <= 1')
                self._entries = x
            assert isinstance(self._entries, _np_.ndarray)
            assert self._entries.dtype == _np_.object_  # type: ignore
            assert self._entries.ndim == 1
            assert len(self._entries) <= 1

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u32(max(min(self.term, 4294967295), 0))
            _ser_.add_aligned_u32(max(min(self.prev_log_term, 4294967295), 0))
            _ser_.add_aligned_u16(max(min(self.prev_log_index, 65535), 0))
            _ser_.add_aligned_u16(max(min(self.leader_commit, 65535), 0))
            _ser_.pad_to_alignment(8)
            # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
            assert len(self.entries) <= 1, 'self.entries: uavcan.pnp.cluster.Entry.1.0[<=1]'
            _ser_.add_aligned_u8(len(self.entries))
            for _elem0_ in self.entries:
                _ser_.pad_to_alignment(8)
                _elem0_._serialize_(_ser_)
                assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            _ser_.pad_to_alignment(8)
            assert 104 <= (_ser_.current_bit_length - _base_offset_) <= 280, \
                'Bad serialization of uavcan.pnp.cluster.AppendEntries.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> AppendEntries_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "term"
            _f0_ = _des_.fetch_aligned_u32()
            # Temporary _f1_ holds the value of "prev_log_term"
            _f1_ = _des_.fetch_aligned_u32()
            # Temporary _f2_ holds the value of "prev_log_index"
            _f2_ = _des_.fetch_aligned_u16()
            # Temporary _f3_ holds the value of "leader_commit"
            _f3_ = _des_.fetch_aligned_u16()
            # Temporary _f4_ holds the value of "entries"
            _des_.pad_to_alignment(8)
            # Length field byte-aligned: True; all elements byte-aligned: True.
            _len0_ = _des_.fetch_aligned_u8()
            assert _len0_ >= 0
            if _len0_ > 1:
                raise _des_.FormatError(f'Variable array length prefix {_len0_} > 1')
            _f4_ = _np_.empty(_len0_, _np_.object_)  # type: ignore
            for _i0_ in range(_len0_):
                _des_.pad_to_alignment(8)
                _e0_ = uavcan.pnp.cluster.Entry_1_0._deserialize_(_des_)
                assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
                _f4_[_i0_] = _e0_
            assert len(_f4_) <= 1, 'uavcan.pnp.cluster.Entry.1.0[<=1]'
            _des_.pad_to_alignment(8)
            self = AppendEntries_1_0.Request(
                term=_f0_,
                prev_log_term=_f1_,
                prev_log_index=_f2_,
                leader_commit=_f3_,
                entries=_f4_)
            _des_.pad_to_alignment(8)
            assert 104 <= (_des_.consumed_bit_length - _base_offset_) <= 280, \
                'Bad deserialization of uavcan.pnp.cluster.AppendEntries.Request.1.0'
            assert isinstance(self, AppendEntries_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'term=%s' % self.term,
                'prev_log_term=%s' % self.prev_log_term,
                'prev_log_index=%s' % self.prev_log_index,
                'leader_commit=%s' % self.leader_commit,
                'entries=%s' % _np_.array2string(self.entries, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
            ])
            return f'uavcan.pnp.cluster.AppendEntries.Request.1.0({_o_0_})'

        _FIXED_PORT_ID_ = 390
        _EXTENT_BYTES_ = 96

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8Nz>110{`t?ON<=HdG1~AW7y=9O_3s(5+#->iky{aXG!Ye6=lU@_=wic7x<8fIP$1wx^}vkJ>BE(o_z=qARl5#!2lUR6Trtg'
            '`j$EBma8vDkehSJ%Rvwaz8DA)JC`{BU-ef_PtUGID2U?#62PsR?t0h%ecxY?*2gn{@#`y={I7euz2l``SgoZZ33wQM$m^k~)*5lE'
            '9j8Gi`rU<VA`Ds(^&afBMgOz@(hvF{^~>G4S`bAd>HAi9;eM8M8d)b1<4I;~5pO{e<qqF$@Tl63+SNwbNi&gDue94D@~%f&5{R^V'
            'Pkg^4(yZSt)iy<v262St&c93X&-(6^YyGhQgMRlwjc1Uj-pNGTe;+E@qX#BczdL&)5TQ3}mR<9B#%me2b+7F01p6FpLW-jgqcmtn'
            '!dr_n(G<ye9}m>(K~@Vz)Xe<8%b@TEPqSJp_C()5**$(&7lhfWSK-|)d<8wS{<MFu-#u1KGah+7@$v<I(y9A)cLoNk)$h*KytvWt'
            'T77u<w5rx$^q-~J^DgsG`!D)uRi1@*A~tJb+^osW{yG2r9@(6HwnHXc5P4$ziSsRlf_oxCgMn^Bwr=^JSQiP)VwU-W-Q(*SYx6cd'
            'S&tJYw%Z|(cm|VN9qUf_**&H)N%&5`d*WRVPvOZ;IX+kL>G(V>)I=y+BFfaf`tww>-Cf+p`q1un`u;)xkTxv;2pH3s5AO_(>R0Th'
            'f4O_?MzAfsz53yQJ6Chb)ZE<<X4U46AlvD?4p>AzO#9t)ddx<a1H+dUfA_lw|1ii@jrZXv)z#fsi`)G!+pCatr&W)`04(q5Ezyc$'
            'MzBA3ppQI@lRObL`~dLf|4H|$d!j9}VE1&>wa3tQpF_ICw>x3TlbvEBC~K349nt^ue%USc(mM2frq&9gzWXso_%=r75nY{-W2x>G'
            'CbfF*G==*xobI_Z^m`V=eLZ)Mp3hTQqWAmhx2>vl4`4Xoa}Uz*1q=`L+(VS^Fg<rD{}BxL_uQxG{ZR}L_1t5W?rC~{9K)x2?g<PR'
            'dhQ~<KS}L-2E)ak`z(gXdhRI<ou2y~h6j7@^OXKHhBG~vQT;Dq_*~CDgW)qh_eBg(^xU&l&Px~`>AB~qUFWGkWh!q8!`YtuGPUy?'
            '7{1(dD;So0?lOkwdTtfNvpshO!!tei0*0*TUc~VEo_h(yQ$6<;YR9Y8pVu%v-g954_I#7ZVU_y#2DR%l_47>(?VkHBYTsKJ&h^|s'
            'pniXw+W9v1{~Zihd+sA@uTS-EQ~pmd{J7`-h{7LJ_&J3?q3~xE{({2asPI;4iXw|TQr3}G9eGDb9_fg$BilOiiH`h8M}Dj$pX<m^'
            'bmV6`@(UgL4MjR2Fu*Q6lDbIG>If7dr~REM03EFb9x_z*q5QSHc8$gBz*0fVco@bF3F9}}ha!ntu+BQs<0#%L^3;ev4-tJvAY0Y7'
            'YZIjT<r*=oFs&qocaP>2yjI^)KEg+R|L^?2O+ijQ0a65w6kh++?xET`vSqCuCmD9@cK1jvjXOz0z>84S+8o3Z#0!Ejs8?&)y|CZi'
            'e;1sW?YsE$vwk;Sc?hDCuB4*g;>oLTyuNZxq>r<>y%LHzm4BA+UwVCcJq((Dwv4_Hv@KZ?+weEy;Yzzx2Og{?q6w@64IB9n>53Yi'
            '6&#(FwQJRj)eBXm)4mk<qcxwW(8vUJ3EHq3G(`VXn47=4Cf0*Uz>F}=33F7nAApVk!v(EQi@}Hm9+Tt7VBTO%z*&MqSR6^c>A<ff'
            '+zFy4%MvgK93K|)9gsHrUCfoTFy2Ca@_EEAURq_)2AKXWzLQens8e7Mqx@;r9@Dh6EgHdkpzK8^Z^ckZ5Ut16e%F!nrX0lxTBe+_'
            'IW-*MvtYOS-Dxlw(LEvOsg}jHB#twgF$FOLllYfz{eORQ<Xrd<{YTO~{qOqUBRiE+beDS`jN^n}!CPNtc&w-@t%G;kR;l}L2~4{M'
            'b{@gMcuygkDhSaO3DL|RLNrf8G)F=-OF}e5LbR_SL{kMJa!80A5+a9$$RQzeNQfK~B8P;?At7=|h#V3kryxWQ36VoW<d6_KBt#Ag'
            'kwZe{kPtZ}L=Fj&Lqg<`5IH174hfM%LgbJTIV40536VoW<d6_KBt#AgkwZe{kPtZ}L=Fj&Lqg;fgvcQwa!80A5+a9$$RQzeNQfK~'
            'B8P;?At7=|h#V3khlI!>A#zBF91<djgvcQwa!80A5+X+nk)wsk(L&^CA#$`3Ia-JuEkuqMB1a36qlL)PLgZ*6a<mXRT8JDiM2;3B'
            'r`Pd+N)fF-^9Xs;o@Z|>R@+5+P-ukz_lU6X_&5B&_HS-{Z_2X#zv=k@_^JO-xBZ_3D}3}jplnzVtk8O3MXm?N$=m-oB<erA6A5-V'
            'x~pkA*AXUUCg5%8AC`<v&0!S)R4ltq%YsH6r6Ni@I0(%+2{OM`Wp`oSlnR#Q30Iaewl0>e>xqm9VOs6`zZ|33eb9k^cb>Wc%Urdn'
            '5&p0K&uR5PO)O8fPhX8A6!vJ>g#<2fa2)|!iBj^#rEP42$;clYI}qC|eV)J>5V-$acS`a$1Kwtew>AGh(L!Rnu#lJ`-kv4io+jS5'
            '3k!%j;_VsY?dbw<A12;DM7+H~ynT>(`vCE_O}xFouz;8+-ku}go+aL%A>Q6cygg04JylphFyd`Syv>NW8SyqF-e$zxjCh+7Z!_X;'
            'M!e04w;Ay^Bi?4j+pMsFV8q*uc$*P#GvaMVyv>NW8SyqF-e$zxjCh+7Z!_X;M!e04w;Ay^Bi?4j+l+Xd5pOf%ZAQG!h_@N>HY46<'
            '#M_K`n-Om_&D%`#Hq*S#G;cG_+f4H|)4a_zZ!^u?O!GF=yv;OkGtJvf^ET7G%`|T_&D#*E`!$gw7zO}_!4rU?=*(CJXJ)S8#8?D|'
            'xq=fjLtvOAFxUk!%om)P5`n=YFf0%l<_HYO3r>tpV3;8=oFp(DBQP8$FxUi!*#a0&5f~N;495yi%s~P}iNG*JV6X@bFA*5d5ExDq'
            '7)}uwP7)Z76Bv#boR|dygH2$VCos$q7^VmeuM!w85g0BI7^(z@3W4Ee0z;X=aE`!mmcVeP00!;EyhC7EB`}l;42uMY5`kerU>Fb>'
            '1_Xuyfnh*k7-%pIG#CaN3<C{@fd<1sgJGb-FwkHaXfO;k7zP>)0}Y0O2E#yuVW7b<&|ny7Fboh3za^LcYcza~hOg1^A4(dA0EXdL'
            '@ROzre$rIIPtxmKtKcWi6BtSah64pK%oY5k*~0p^L}0K842KJT(iDN=7=hssfuTfTm?khhLtuEiu)aM&V3;E?Ocng3Qv`-Z0>iPw'
            '`t~4!p+sPqAuw13h9v^SIRe9r1wZLI0>d)|h7$yaV+4jH1cpNdh64nK5`kfsz%Wf<xJ+PJB`~~BV0e|laEZWhq2MQ31crAA466i&'
            'GJ#={z)&JE3<(TF0>hBNFeESxH5i5(3_}fup$5ZHgJGz_Fw|feYA_5n7={`QLk)(Z2E$N;VW`0{)L<BDFbp*qhIwiD8Vz5gL7^dM'
            '9dh^MfjiZGN}rys<8d<`LyjNjz2HvCMYG%(-)-f*%epqdhQ%YXu_g71dpv52FFJLbt36idW>Zjl3}s47ww}<EtqEJUj5S-vo-Je1'
            'ma%DT!m2G}*Oswt%h<LxVcnLoZ_8M?Wo+CsR&Gt$xn(TfGPZ6RYqyNOTgKuoWAm1=ddt|oWh~z^wr?5hw~YN;1_74AfMrl%85~#!'
            '36{ZvWzb+5JXjNmunZ<Fg9^*w!ZOIP3^pu-4$I)fG6=B@Ml6F8%izQ^NU;o7EQ1!y;KeeCu?%J`gBr`=#u_2VlGssBMhT4Z^C$7R'
            'C(m_pfE2YFzgwn~##q8<wuv1e=pQss7F29n)9mPc7vDOR{)l>Vh>TIbQ=YilrjgGS<(e(_5*cF&Tf1o9om8>?WQ?-TXI1RDreCw&'
            'UP7<;c~iq_6?=}1v4jTof{Gm_W0dWD(bRF)<b6rS&T4PnY~_^DK+C4QB^5iSso8ABm(V~f)U#z%Zq@X0Ma8~B##lmU;G&AXM8;S`'
            '@A?%LJ59zY>witfPLeUovG}Ix*{W&D8)n=uoAG&5#pd;yF}CV06`LYsEV<tzV=ST3zO7=b+89gj=ecccq4r+;{<%kg34HlpoTM3R'
            'sNLFjsL#W)pd}dI_qY*<>Zq;3BUTrTwo*OD)62Ha*p|#ck@YQB)?3Q@X2%kHnUyawsJ)%y4ss;6Gj$zDzDd*_DHcSTNH%#mR{N4|'
            'U#~W+71j(kg*qdgNDoC`sJ_Nh(TF22t;j@MU(h?;e7<_+Hmi417O2kPNg_5og$C)CzML-=`h{ueSJhU#<G4W%mGM^GiPYvemLFtn'
            'E5H*-{#aGUq03vN0nK7)6YieN+hy=}y#uMKnR<)e3sO2v_E;D<<uUfrZs{s!<54y`&Rg8|Vhv3AscYA7TzPo&LG9Ms?b`L5*RMWU'
            'yK}qtVC~lRI}ab=VMgh@sypw43U{B=*JZ?ZI}s@!!;jq-E8UYL$U|K-<k`QT@CH6j;r$JY;}x)Jcj|}W51{33{CpoN{}VO!%A?(y'
            '`se}_qFZbKkuil<5Xoa@5sHSH-?#%~8hJ7S9U`za_)t{rEO!!(Gtg?`>9aR!QDpL-NT4dTc$h|<JY_6U#204=3_!~!TD8Phz_=)N'
            '3O~yE=CNgVamkja<&Z*|D^Jr-OQ4bQO!nudyp=X8BaXz#t~lBf)>UC?Z1N=He2TAHahl2Wcn*UH><u1<Hs*<T;3Zx$tFrr@h7UdW'
            '`DOri3+5fSp+M*o3;~#RBN054r~92K0LyMk423cGDvXDjA9tEQrbB47+Unk#?8&k|bg$ZX>QHtk4R<QLqnXA&cg!z)5+H8~814$x'
            'nK3_TLf6zyf>d4th~jK)R=C6_bdB%W4c<vd1C=5I!E&+yI>W%)TO99rn)!mpM~XTCi(uj{Y)zU%J@V8l<U5K0gfTaBp&<doi(4?8'
            '9+n~dhmI^O0|qM$towZ!s751B<P1z)va7NODvK;c*+3J1c0!&2k=iMYaOmOiz=+^Uo0`!UuuY)QflX9nQw4->{8EDt;=h8pJ2OHi'
            '9ag^NANMPM*}v#7`>*?#HvR#U`KufM3c<!d<DXySpMQrx`Gd?)f5!)zue@=gaJ9B@sQC%7M0muqzS61XgUPp$8*D~hCsDkC78>!W'
            'A*eh%Ptm#K(+ux(!W?B=0%$4`UMKQ^v2_v<CRL%L6tn}-od!sb%pD-tG-TCuCq`^Hd^Doeo-A{h6I@yTTE@H>3>HDb+wE{i+nP4('
            '2r#)@(*RvUqQwpfcru4nxndWgsVU@<0)=F<V`#UX#0}68Rnf%xGENW>Yk;%@8BqOpR1sDCy6&tQK*}f(=8>0cszkj9V}&d;0vvQV'
            'i9xs!+rXVEZ_)|0hgXy2YLd`v3}7_Vd0&C7W}@4?kpLU)I<d;;)_IUXkGufrD6_|j@XKtmg1jZMk@}-PNpi5ytVQg;;0aJPlmf)~'
            '5N}JVYu4DXtERXsrf22r0658qbmx5O46E<3Yk_FS>`v6=Ni2u;JFy?JI}&TaF`2rxHL}nQa673+iBcmpSq>Z&@B|#6%pWzG23mF&'
            'oEYqI1~^I?`J!?(aBk!gKPyvrQ>0vTn`)`Twot~H*c6aR-cA^mWCjy2Fxye5RToKx?vl|p!OF-Th!gN_+OZNqZJLU`%P{?TcQ8e%'
            'L9LTiivX${l|m~?;ug$tiqqM!v4|xJ=R|=0h{~uv*kA1*P9P^sMYs;5b3Z^n$@?X$2RJZ#jI>?v0zdkI0cUiiH962Jc~p&p_So7Z'
            '$Gr6zFWY$&jZY)q2A#>&1v<ROfupBpuhmvQ9$+>isT@h~_d8(lUd5Ka2MDizBf%v*G2s@Bp<%?ww*8)u$d5+QLRyNI@d>8x=8r>3'
            '=|n}&oG%)W<uqoy8Xu=CE)wwpdQn@EO+%(^MOgqcXmmcS<m=>~m+CwdcV;xnVr}Iy6VzS}@(Y->Cvjpcb0aW;nt*$i9~CoJunfX!'
            '!b#JvS+m1odL%0vIGUc)eaKOV$yu<`S&%KQD9><RUVN1P8qQQCkhQt$NZM)3+n14Oa$Eu^g9hX@(4vr~fM(-#WPLd|CU4k;gDsd^'
            'u^dOF654VDba3LW%&*8xo1+m`mIZ~icqCm@*?&MUfTE#g1Y9Z6mS_O8lQmx5Y5Slnl7}~iA2d*kJE@vh7?Aa#*-4D;QHt{^8{PNR'
            'g8}Oxpl@g*jD^x9z&_GIl!ZIs#)jTlYt00=;!V{raPrh*53&gjNp<xJmxKAtFoMtw@bQpp^D`MsBeO>e^Crv-@V`l&`Z#QLIa275'
            'L)9tpNC=`Jq?Zlc8H8#kB2d&gc`Ps9g85chj7G2(kiO?}WXlCC?__Zcc}|IYmWft7Q_EK={4~Gdg(4ja?XcwZP!YGh1SUCa3+zU='
            '9f(JZut|*mJ(iB{?H0~Hk|0O5!*-re4Xuq0F0MkjZZ~*7xp!DmG**PY8#CsbP)}ejgC9C+*I^`4*8rcfRG>X%3ecVf;n=b>NNwfa'
            'c$67EMdifgYsHJ|dv%r!AN^)|H-2o<F!Eqp{IMcOTi4A)x#AnM`DJN}%d!9oMR1Ry{h3;6Wg~0Sxs(@LXfDx{HWd=Nk#MPv6dEMm'
            'oU&AJ&;T%65rWA{3&W`fBU|>M4G6X+u!?&)j;&G7mcW8jKWH=U8)|7Gj>1J@stIQ#JZim2J1{vifI6<E%;!j_AT#o#rXU)5TTKy('
            '1V|+BmQ$bixG}jd<O;HqA0;)GTRej~g(leaJpy?SG)UmA5|9Zy*gUl1ysysp^42Satn_itr_K$9J>fGDOLf{F&qjXxE;Wvest?QN'
            'P3>1{8fnGgO~;C}unDrm_81kBGHAVyaM7<?C#}3V#n?QYIQ7w;xv%f@WVaPoIjD-N+SJi}xrCb;pnX+#Z#VCpmd|ogG$OOOjw-2!'
            'GU?<+n<gFD8X-(3YL87|88;TlZH%BV+*>kBs6E}bkrrOoUdmXdJZ~g6j=Zt_vXHx>TzeAe9$;p*=Yo5KVTf>$BBSPMT=gKCD$4`T'
            'h&nj^OKM)#V_V}gz%OOf0Glise;s#6_Hsr6Qg@I~WI3G#zYC#BQB#k0rx%5}yk;K@Nm0ORq$%Xy3(P<Ci4w^r#b^~+wXfv;Lb`*!'
            'rKAJaKi+r+=<Um`8*Cm7b{#Aahr|m;UIs9r+}K-YV~QllN_8g8xj3pzRhfP*ON$$~M!U@docu7DCS}-&Jnh^|BUT_m)tMX{!&6Wn'
            'lWs~VumEraa5Sa7AZuQMSu=3T?NxvmzrGHpWNaTCDpVx2PZ3BIDiz<t%4o9#cj%Xamg%Wk3Ba-%^#)e!V3gsP-rQao+p&Q+`g7>t'
            ')4SYHc>DVIE&Z3@2KRq@8y*zXsZ+|gA<^5TL^^Nbaq*KOmG>?rx;vS-@ObyUA3&lH@_E%=l<~(KH}_eVO7Hv8t;MOy429?Fw97x>'
            'AM_pd?elTJ>@WM5{8hD`i94D9ldaE<|AOCU&v9dF2J-yBfI)Y@CcVh4f6Lm}Jzn$Z|9_CweD$q+@n#3}Pj9T@kbKo^9c=7c$Hsf+'
            'BxvK0aWDFVg6*mgqy5%xm{DsV&Zs^&Pvz7~JHVH0mzS8e`rln^L(>96000'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     term:    None | int | _np_.uint32 = None,
                     success: None | bool = None) -> None:
            """
            uavcan.pnp.cluster.AppendEntries.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param term:    saturated uint32 term
            :param success: bool success
            """
            self._term:    int
            self._success: bool

            self.term = term if term is not None else 0  # type: ignore

            self.success = success if success is not None else False

        @property
        def term(self) -> int:
            """
            saturated uint32 term
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._term

        @term.setter
        def term(self, x: int | _np_.uint32) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 4294967295:
                self._term = x
            else:
                raise ValueError(f'term: value {x} is not in [0, 4294967295]')

        @property
        def success(self) -> bool:
            """
            bool success
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._success

        @success.setter
        def success(self, x: bool) -> None:
            self._success = bool(x)  # Cast to bool implements saturation

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u32(max(min(self.term, 4294967295), 0))
            _ser_.add_unaligned_bit(self.success)
            _ser_.pad_to_alignment(8)
            assert 40 <= (_ser_.current_bit_length - _base_offset_) <= 40, \
                'Bad serialization of uavcan.pnp.cluster.AppendEntries.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> AppendEntries_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f5_ holds the value of "term"
            _f5_ = _des_.fetch_aligned_u32()
            # Temporary _f6_ holds the value of "success"
            _f6_ = _des_.fetch_unaligned_bit()
            self = AppendEntries_1_0.Response(
                term=_f5_,
                success=_f6_)
            _des_.pad_to_alignment(8)
            assert 40 <= (_des_.consumed_bit_length - _base_offset_) <= 40, \
                'Bad deserialization of uavcan.pnp.cluster.AppendEntries.Response.1.0'
            assert isinstance(self, AppendEntries_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'term=%s' % self.term,
                'success=%s' % self.success,
            ])
            return f'uavcan.pnp.cluster.AppendEntries.Response.1.0({_o_0_})'

        _FIXED_PORT_ID_ = 390
        _EXTENT_BYTES_ = 48

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8Nz>110{^{L-ESL35VzGdPLqBrGzB41SCrsB<Q&?nrGgil0s<4)a!6k)Snb`7JxkWRr`^3MMnY;IK#jB#k+Qt=r!sq&CQjSD'
            'Ab}<O_GWf|^YxqYi@CoJTaD`DZx++s<}zUxjNnrI%2Npm%k-qsRyYX$(i4zkLdX2aX#wFd+<6&(3mretgi>GvHvFY6XUfc#22Ni&'
            '&lH~!#GR7wW?UtODw0f=)`3aBDhg2f*UA|IHW`8~w6b(}f$f5^LaPYedUkX^483Nr@ke+W{1W4ijMCD94L^~WGg3Id75w>c1jzg('
            'u0@t}$C-=4o@HK`n6%iX8_V0uim`(HJLO;u=5&%vEESGPP-BOo*Cz0cTgN6khkzgWmBDMEXqIe{ZZoPVqsH%H82o$8I<9hV@>!r)'
            'Wr~Y_jw&??evaij3%(IZc)fOu?-TaYW344{bt)kIsMo}s_%YtzuP|D+%rdYx;HvKoVFae_blV}chkWGP1usZ4(xwf2h2)Ams&_)3'
            'z%S2Knx)ganbE^1xPl3GO3FQl!a&A}9bw;JW+Sl&IV-erOyr^OuQ97jlL09tu!2)&{&IXsktR&)jLYCJ42WubgQz?Ve!sg-ov>XC'
            '>4cm6j~;ZNfZcJr=t|JG`dQn$`(SM(#TeaMWGV${y0AyTipy?Mrcz|gz_^q#u#;xnZcW545wUwj#O}RE>u-?pvt&Jqln7OSmKkzO'
            'p&L*xa%5Lz5MJRbe(JAQC8>u+k-FyNeC;IobL1xY){!Hcq*HE)>c^}Hf1@f6bD9~gU4?54PM+|gPyhRh)Tz#~R8m~4uP5S!kCeE3'
            '^F8>BkA?f8df%egBLez!OjFwJvq0>0l4=TvD!U02P4gBR_mo)3oi?-kB||||i+z7(!1G+F@mrU03kS!izQ4YqRpg?2C#1hnBT^${'
            'pJpt#XE3hxODVaTzGXencDXDe{24mE_JK`lQx$bsw42J5iZ>A|E&w|4y?AKFB|sIA){BhBi>qpx^=U4l0!55yO+o{k;!f`tO8QPn'
            'q2r}rdJAO~cSzhh7TYw=H7?;ryo%RiCM(zhT%Vmxyt|M0`gk87;^(oo_(jE7{PN!t6gU1)BDPpGQ7&x0X!;deGW9=@VF)~@N42@}'
            '!{de5riFK_*Q_$V9arbK_<ddA&6zeouSGw{lFimXcJmaEZVb5^!w?E^;w*CR)LmXDgITPFgQ`6{eUub?>{)Li${Po^YF^dnsQmjK'
            '%4nMW1CCzV*q#Rf00'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    def __repr__(self) -> str:
        return 'uavcan.pnp.cluster.AppendEntries.1.0()'


    _FIXED_PORT_ID_ = 390
    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8Nz>110{`t?ON<*wdTx$JGgRx<vSdlNB)crjGDqfcB>5%V>#VhsyjI$JtR7w`S%WUJYo>eD?B;ei=i$VGd|1Z{2!wzcV2?cR'
        'Ej;>`WA?mB7Cz;W*BU_(>}3H134;88)nCPClOt;t#Mw=3z|%!`RdqeS$6sAV-JSjOzxu8v|LZ>4-t<y0tkqMI1Uw8r;Ehn!>dm;-'
        'j?*9${qD}2B3TQX;?`zc^grz{eANH2U+M0yC*p@4k!JM_zxS=~?u#M}T2RCr&pB5QqDUk%%grq5G_y`psBC*Z;w^YorNh^nJgT*$'
        'cC8t9(o7_^^X;~Xyh~A*1R|~7P!H{Q%k?#pq(K~Ez4Px-`qRE!a;=a1A3?M0JcBZgPA1a+d+?AgdTMg@yW8IkMCgs0W!F8Pan-@C'
        'inkN&bFc<E_TP@uU?mdX<tP&?A{p=F&Uz!r>Y<2MGQaOKsJzKx^jfh8qxVGj;B{RQ7OP!=dspxl^vL>A|3<%ipq^$t@_6FqEBd6<'
        '@b`9SVW3+5?rhzQoBgiUhc6#jkM)oFj8ad#%s=5*`~_8JcRLYl^)Ozk%fkM1eszmtPQKV4Q!I!)vGKs=c87v{B0*q5H=$U!aziYO'
        'gk>?ye8Fz;<&3p?8@^eN6DBs=A&+<llUf_=PWQ+b)0iZDv)?`R4u@~yo44iooX2mAz!jlriAV!?7uCGCdw2@^5O<q>f1kf!1Is@M'
        'VEXFeouyHI$Zq=I?jCqE*bv@U{qQg5o?JFh?(P6swRtnhHv6svh-idqzk5=T*$6o>d|B~xzq{)@L8hK~6F$<jy4&h;yWeG7Rg!MD'
        '8gUo^^7da5tr%tm`*RKY$g?=f3qjKlfL}iEK5|2}MHWoYH&ed@ZTFWU-`=a8FyzT*F%#6a#>0;2|5?A{mV0RfdOllk1ySF<iwVAg'
        'iFssKC*)YGTf(eX&z+&`HoVUC+*$g(9k1JZ?i_tTPuDWt-$9>k^+<OoUgvx6F8aJ1uRDA09?G|uzIUknKD_SexsTBO{dnEea}Q9y'
        'N9p^6czvYj9>VMHo_m<?KSu3)9IuCa?h(8m=($Jn>h#=Wc-_@=pP>9t;&ry?GJ5_~cs<s0kK^_6p8GUj5B1y=RL?Vb-PdzZQoEj|'
        '{#2;G1-x$Wxu>X|&*Ak{&#mIM(sLK_da~!%@Oq->F5&ff&pnM-)^pF`^@*N)7OzKp?(@`+7pOlk;`Lz9eTmxhGL6GI>fbBWu2-p_'
        'ui@41x!<Dpy^hzpp8Gr0?{8B(-=O}#h1YXE_g!kQPtV<;@}J=KZqNNOU4KH?&*=J7x_(aAFX;NEx?U-lC~;UPDmrmaC*IPDcXh(o'
        'i4C3jL??c%6F<?3&vfFaI`O$qe4!IxQlbL}1M0#f>5KGT1Bn9Sw4)OR;G^}xLxrl{mY)_cUu5wzs8o<L9)@vK()cy@fk<K&EVE8@'
        'CyLjLIyI8dJtUtI*jDZG#R<{;YLD2iIIS#&clYNUyx!PUF~Wy^|L^_3OTkV(0agT!6kh*ccTas8)w14>lMK6cwY#sL#+{@o;6^Cw'
        'Z4PD$<^`89Xw>T1y|CZiaUFu3jq7;x(|$Kyx(%k1E~TQ;;>ioIytH&tq<6Boy%dT#m46m*o_%R?ISf|(Y!PE5Xj`%*HsEi>!=-ko'
        '0Xhhg(F&*zG;9<<q)TdamT+{IE?=yjshzH&oc5);@2~qjg+?amOR0*t`uAXN{_>(&4k7_F!muRFQO&*uJ^~6Cv^p&YBNli}jvIq{'
        'gE4_%2`XW6B>koXpOSDhh*nsZ02pw5SjacQ+U$3*RLa759sSAY5j%7C9D_E%^sn>HlqyG`0z8b$r!{-b)6%wR2FroMi_G4Np^_k4'
        'j%)p{Bj-&8lo7N{1!Hq+I3Q-hZuPq}02t9dB<HD~#q}hPGg&YNGXqHcOSkbqKRI$P{NMNAlkoK4_nU-MX+_t$=fOBm_!Zo3sRC^!'
        'RcQmF)3(apcgq0n1aO|h|JjyCR4N!ziHvA=3nQ8*Bbp;4+D=9^OGdP<U__;Y5jkW;4jGX{M&ytYIb=i*8IeOq<d6|LWJC@bky9`t'
        'hm6P}BXY=y95Nz@jL0D)a>$4rG9rhJ$RQ(g$cP*=B8QB~AtQ3gh#WE^hm6P}BXY=y95Nz@jL0D)a>$4rG9rhJ$RQ(g3P$9R5jkW;'
        '4jGX{M&ytYIb=i*8IeOq<d6|LWJC@bkwZr0kP$g#L=G8|Lq_C~5jkW;4jGZ7jmXhP<Y*&uv=KSlh#YN1jy57k8<C@p$k9gRXd`m8'
        '5jon39Bo97HX=tGk<;t=Kcj?ppLwJ_dC!rnO4X(~4;qc|{{b0x&3FC3@xQm)ELoQS^N#;d_xyjp>i+^%;lr;%vSB^2MC*YixgHo7'
        'Z~xy=sQ>g@B-r)nx|Zo&N0^X>K)0cPSTia$hgASbvFtW23z~71iYV>iAgshmkom0|yAJE7RIns3xU!D1b+J@kPh>m@(^}vE<(R~7'
        'gAVk&^V9`c=Bh=F@PGBcF021(QhBL;^g<k=u}4!E61c>{bp&`NTFL!uTm3_TjQp_r$B^18e_p^D2>9wOWOhqZx*13}Q_`&^_<`0E'
        'GljLpEJ^ovlI|IjZo9CCm?P<)CF!0iNcUcn?mZ;kyGgotk#z4Q>9$F_cNEqT^CaDKB;DIdx@Sqcw~=(ukaU*{YY0Zt%}BZ#NjD?u'
        'W+dH=q??g+Gm>sb(#=S^8A&%I>1HI|jHH_t))0)On~`)gl5R%Q%}BZ#NjD?uW+dH=q??g+Gm>sb(#=S^8A&%I>1HI|jHH{9bTg7}'
        'M$*klx*16~Bk5)&-HfE0k#sYXZl<N1Y3XKKx|x=4rlp%{>1JBGnU-#*rJHH#W?H(LmTsn{n`!B0TDqB*Zl<Lh5)I!IDUx9TWEeaE'
        '8H(|YRfuQi3UQ1@WSA?&F|$O5IU<8yAj5nijwurvEF!~hBEuY!;b0+-v55?`M25$R3<rn|dx;D-kzsp*3`dC!hlvaa3USOXB14(T'
        'FiT{xhz!pV8IBVfo+L6HB{DolWH?A<*k6cab`u$FBEvk9VV1~HA~L){WH?J?I89`z5gDpPhEqg_3X$O?k>Lc9;dp@zI*xgZ$Z(Fx'
        'P$4oLCNh+X3<Dy=fXFZ)G7N|e10usflVPCAFwkTeXfg~m83vjR15Jj3Cc{9JVW7z{&}0~BG7K~s2AT{5O@@Ic!$6Y(666jlu>Xb-'
        '-w@*eJt6#mSMD$bG7KLgR4NrhrBWeO(yLsn5Gu_R8OlV4odq(?6+)%$g;j2u$Y2o}_7*~=5|QBmkzo&!p-g0$Au>EpWO%f&%H2t1'
        'm?JWj3Zc?bBEw-K!-2vocNdYNOk|iPGFU{01tP;qBE!>#Q0W+v;c+6vAtJ*8BEvo+!yY2TP9j5@$grKrFhgW`mB?_8$nX-8;RPbY'
        'St7&fLa1aB8Qvl?oFg(+hzy5`3}qt2kjOA3G7O0fLn6aalVPaIFw|riYBCHp8HSn+LrsRECc{vZVW`P4)MOZHG7L2thMEjRO@^T+'
        '!%&l9Sa64L2=NUe6d`f|k*`61&n<Ny(c5UtxbIB+k>k61C*6`<J<B)b)0WUv7P$GvEbfhst*sB;;L(b>-}c*F{f^o|D?#lU)G3i{'
        'Js^^;2`pO%&6dHlWe{x{Oj{GEwhXQ<gKW!S+nPYPW$<kogj)vVmO;5Sfpg0s-7;9W4B9P&cgrB&GMKjv>MetN%OKw}*tZP&ErWl{'
        'Fu*b#unY?<!vo7O!7^O13>z%N2Wx^6mf?hDSYa7nScVyv;f7_{VHti{h9Q>Wh-Fw}8J<{%DVE`iW!PdFzF3Aamf?(LSYsL9SR>|G'
        'k~=ESC<7Qjdyt@ea)TEKNJ*;+y=5*5#xj0qo77IC{x0*)Zk3wRGCSJn#k&sW->1IWLtvEmR4{H{*2wRa<eGQwWddUvTYK2tdrYNv'
        '5E$h%kEql^Ex+cydl>`YC(IL`RH<VG#xerxDV5q!V3h5A+C1ZgDf^5{ozMZhd7)EAfL2U>3o3O$OS5?=Uq*mdsb`C(-kRy-l1e>C'
        'U@T)ia7Lw`AuyIPz<yq(o+L2J=f9{@j}aK<SiEd{cFwfq6*KOyn(=u}rRMeKF}CV;l`0V!%kH-bjAaDv8!B~9gR$&>mV2Kq)JxdD'
        '|J=KO0eboUI7u_sRIhE@q23tFf|g)-@Z-%mRC{hs9<hdC^iI`dJbl%+8C#d-CyKt#D*D~BKH{;!PO-{a22XFN_$oOP8<{$nBk#}&'
        'Efz$XNY;2b_VfkYzEoSORoP0gCe&u(M1H99bnQi!ie?;nX;o%gzfbS*E%b%+S6QQzvOskPw-mA2DKtp8^i;l9=ojXpPc>V;CdW7B'
        '@G#zrJCS-zj`ar_TMuw6lHXAe<Iv^x(ST+#v<Y9M%VTD6cew+(shRp+yBDOitL(8bUXlCRhr8tqSd2&6XkYKx)Dt!^;YTlCdh`74'
        'w{O+2T)tYr^!B9-w=Q41TEBJq%B5?!Z{e;+`43cg-UAoz9@FP$#6~+2DelLQ9UCj(kR!-L{bVS!V>#hX{5FOAZ&Di1g3Y+4k0BmF'
        '<gNZ<8#(_2HTC?v)0+D3X{bcE*8Z-6LMw>m{;~)~)68$&fiaCdnSpi_SQ>mFs&<y!lExWmwQw8Sn?w{r-V+Ht3K0*}h?A$l0#)3<'
        'IB)=3HqojDwglj!+$nsh<eSG9*_j1fZkt061y`P?ot8k5@l5vTZFxLxR7V_%5w19537=JEX>7_Q;@K2$wc<3B`Ef%AciNjg3~ekE'
        'ZNg1FYgS`7J53*Y?(?+(a0~E`+fX5N35Eb*-An|}<TigN3IN$H$)PajUX}4M^W)BnkNJ=qt+qPACVR4|ci(IFwFcDPNyE+RbT-r2'
        '=l1($PXg2p0mEH|XJ*U~R-kL@NI@!314MB)HY;3m6S~GX?I!P}qk&41fq<MWfX*;LdyC^?PcvW8_((|ya1kKh!q%iIJV$O{g?v*9'
        'fG}_~CmRv~UfhD&^so-uKMZ791vpq`fbRETpqkA%kuxxH+OEcKsUorxg@G0L*a>+8LTaZl!l8%510#Z4ZfZtbpf-VG2R2cSO$`{j'
        '`b$kdNdF4b?(B$}v}<|FKjNS97yXy~v;J%T%d7tg+5Fd6{}nE)U*Mnrz&~HYpZt#Iy{~yk^Z8d!7tYugb~ir(l?eA))<bPy-kQ7%'
        'r2#YQT#3>RL}<jLrl9)lyhP{rQ8PT)33HUK3y`Tqc%8@t#nxHCnA8K6q#zE!cbZ^1vUGr2)0B^<!!cr`=_80zd$P_cTe-6S%Ng@x'
        '04$P%x7*>S#+rt81e~1KG+>vIY_S6(o-83<uGmFrY6@kfL7|vz8rf|paT7d5J!oR187ByYH9%Q`0_c95s*0L@Nq5!^AQcoy^T^9J'
        'RkGfLu|ky@5e~YW#9&;=ZP3n?uh3Sshi8=JYLeJ%05F>Ae5^pIndmleCZGmWCstu@nFk5<$O}M@GJ9MIzY2?0)Gf)4)F1Upii3Up'
        'a>Q;5o`6I{Eg+1y@z|6)Z;cJRV5&QBdRDmvgp+zmhtC&|v&JU77>JdaU5i$D63b!z-Pn)VHOV#5m`okt8X+_T-cGtvqTC1}%Rz$z'
        'o<QJ}`J*P&K+DcT5Q81gfJZ5#SX7P%&W+sbXBFyhijr%NRV`H6I@%Z$YXUOKV+y01%wXb4W;^P%8X~FEp)xuzSRI7}aRRYTJ5~m$'
        'p{dln0@II&2vf8g^g1cENT7ysDMU#Uw_uJ_oX)0=RV+w4Cj#&zs-yN`e|3B~!JI4=;WCWQ%>eZzAD5^e;K1lH(zu>NKl&vD&gjT%'
        'a->uCs2T<Bv2{d_Wg9V`y7ML)pGLe5K9i}Fba<WvM^DXOtF2-@;A})zIkMg#b^!2R)t0db7_Yt~$t6265f+TGVWh{l{e2&qAC0Jm'
        'vJ@-u38oI|k5ftcL{-k5FPeAcG-gx5$LXw#WPE^8)OuvokSVMv1fYUO&t}#9Gr8xby3EAk87;E-w8|I+byS1;0+9A3PizG@A``d?'
        'gje}dF=GYGAe<(gG##3)bT~|pR7FEa(^EPaIqEP43pNG|vZYlO87|8ckTPDwnTiCeHdh@<J8gLkGZHHtmjDXTz?>!`3RMbZHcm(A'
        '%Y`v{U=t74VQR%<9Fa?C<OUev#Os+~m8UmHBdU-Em9=;zLsQv*U@wrOsci&8Dbbc}0NBYVUf68=;44yx*MuK5(TY2%npPN)<zS_g'
        '80=AwXHzyh_^Ag2)<GcO&_oyu<w?MOlz}J<HzAA-y|LDs32wz}s$US~sl^@?6Pl9h3=}R0^Mzpqp&1b4q15JQGL|5-M-KBE%nRth'
        '$({N*Yz;Y57?8uGQ_ztROhL#f8?-YB)l5X-sBv;fp1=k8R#}W7SP#hG^E|TU0+x5OxP>~W%stCQtDULkt2BO^Ux-3c4uuX_a(<|U'
        'Tb>4!nzatNk!=Uz(I#v%V|<UbV|crcvyURk(e1FE&!$G!#s(KxAzZf`BA?tnd{8u2g*{Cfb4_R@u$IAJJn7J3WKkD^pRshHEo=(d'
        'o(199vNK3+72SAL7$Zd$#N?lfC)T&>ECC<mW_d_{Y|$`^U|Rf+5=UD<n}>46H-`B|3B^TOfutgY$I$*vt+cWcnsg}@g%+Ai@}!|c'
        'CO0xJ^&*7^NjIk=-5WdrKr2FkoJ1H-HGpi<gEk=97627Da2#8sk}ZK1r+(08IyThSLK=mO!c+^+$avIxk>0@M!~mXgK4m^fIR%@M'
        'zitYmQM9!pB9VZI<im36^A<-ZmxWwGR`a8z#&Vr!FsIN2n|_!;kpm491gk`3;tn<sF`SRp`Bu?-m6(;@$;H&Up|B@n22!a`+vC|N'
        'ZlChRaZ~kS*}SIXDlH?e7^3M|X%;p?cGw=1B60@p*AXuIRqG_mi&Kov!--SBzB32+eV$BPVO4^fsHvAaS}zyyWd?X(jop|QozwDJ'
        'E{aBC7B|o()lep#ylK;<gIXhn38MDc1Xl3H0)>qc^o4s1W(l=r*f#RQS9O#!_E4S&iH##~kY5q<Z7A1~1cnD#SiN(>cY|SwbdV;a'
        '=4ssZAe*Yo1I>s!IQ<K1Ue(vO=4F6CtxW@LvQ+$Kd^@sLFbb5qhI%6F=_L3A5t<Y=^@uyYD9n{L@3Bx61*}F^gnah`^ACNZOmayv'
        'S_RhZ^ZB@t4r8w?>wxu-H~s*O_T{S^Y#t1D1CWP9;sv890~Aoc*jr>{jwHuQbtcS(II2rEng4Q@7GK;N?=}l?io;-<6tIzbI=Gi0'
        'RwO~!nH(FVQ}8?{!<0~91rP?{Xi9rQ)jSWgX6TfAR{>G{@-jflU>^c1bR@*52qX)Yi?8Fu=w%1Kp<e`9rf<zk0G8G0H?Ud<P=;T5'
        'gnRec8ymQze;555dZ_yWk756&<$s`K;r`FA!WYG?YNPTE$n=KElrKJhXW|z`s`z!tbbV^^@jF`-e;+cvUns85r4;UbZ<}SQBEFwq'
        'Ib51rrf^Gbe)*2S&wo_?Ci;lK=%4jp_Fq?TH}S>hf9Fl;>b6<SGOr+4=it+C2P?Ysbs1D<{VUeC?!mf8|1LsO_tkIUiw8ZJe`572'
        '4#~rw@?c}9JXU{THilN~_-gw70+iJcrv2n9%&4^uXH;*ar*di~6!0dSa#Q}+dQV;JKXqoF9&YD;5W4UH|C)oUq(1`D1OKqT@XroB'
        '(cSr-I0gra#(yUNv|Cc8@2S07Qukl?m-!0Ft9Jo}tAB)l{sjMgG<zS!`qf_(u4OYEzuhYSkg8cSy7d%fdTOc$Rp3sgAVI4ipfYFx'
        'soBAa`M*46t3QBdU%6XaeGmKo^(o2e`zXoX(tVU<P@1kJKuPvhGBH&h%1CC4<R;W$bq$AQZ?~Knfsr`~5`T+8_-p+0IsW;%fy9-M'
        'O9fEedno7mdcn|X)cy+*IUm!~M*si'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
